package api

import "github.com/horexdev/money-tracker/internal/domain"

// localizedCategories holds default category seeds for each supported locale.
// Each locale gets 9 categories: Food, Transport, Housing, Health, Entertainment,
// Shopping, Salary, Other, Savings.
var localizedCategories = map[string][]domain.CategorySeed{
	"en": {
		{Name: "Food", Icon: "fork-knife", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Transport", Icon: "bus", Type: domain.CategoryTypeExpense, Color: "#8b5cf6"},
		{Name: "Housing", Icon: "house", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Health", Icon: "first-aid", Type: domain.CategoryTypeExpense, Color: "#22c55e"},
		{Name: "Entertainment", Icon: "film-slate", Type: domain.CategoryTypeBoth, Color: "#ec4899"},
		{Name: "Shopping", Icon: "shopping-bag", Type: domain.CategoryTypeExpense, Color: "#ef4444"},
		{Name: "Salary", Icon: "briefcase", Type: domain.CategoryTypeIncome, Color: "#10b981"},
		{Name: "Other", Icon: "tag", Type: domain.CategoryTypeBoth, Color: "#64748b"},
		{Name: "Savings", Icon: "piggy-bank", Type: domain.CategoryTypeSavings, Color: "#3b82f6"},
	},
	"ru": {
		{Name: "Еда", Icon: "fork-knife", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Транспорт", Icon: "bus", Type: domain.CategoryTypeExpense, Color: "#8b5cf6"},
		{Name: "Жильё", Icon: "house", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Здоровье", Icon: "first-aid", Type: domain.CategoryTypeExpense, Color: "#22c55e"},
		{Name: "Развлечения", Icon: "film-slate", Type: domain.CategoryTypeBoth, Color: "#ec4899"},
		{Name: "Покупки", Icon: "shopping-bag", Type: domain.CategoryTypeExpense, Color: "#ef4444"},
		{Name: "Зарплата", Icon: "briefcase", Type: domain.CategoryTypeIncome, Color: "#10b981"},
		{Name: "Другое", Icon: "tag", Type: domain.CategoryTypeBoth, Color: "#64748b"},
		{Name: "Накопления", Icon: "piggy-bank", Type: domain.CategoryTypeSavings, Color: "#3b82f6"},
	},
	"uk": {
		{Name: "Їжа", Icon: "fork-knife", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Транспорт", Icon: "bus", Type: domain.CategoryTypeExpense, Color: "#8b5cf6"},
		{Name: "Житло", Icon: "house", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Здоров'я", Icon: "first-aid", Type: domain.CategoryTypeExpense, Color: "#22c55e"},
		{Name: "Розваги", Icon: "film-slate", Type: domain.CategoryTypeBoth, Color: "#ec4899"},
		{Name: "Покупки", Icon: "shopping-bag", Type: domain.CategoryTypeExpense, Color: "#ef4444"},
		{Name: "Зарплата", Icon: "briefcase", Type: domain.CategoryTypeIncome, Color: "#10b981"},
		{Name: "Інше", Icon: "tag", Type: domain.CategoryTypeBoth, Color: "#64748b"},
		{Name: "Заощадження", Icon: "piggy-bank", Type: domain.CategoryTypeSavings, Color: "#3b82f6"},
	},
	"be": {
		{Name: "Ежа", Icon: "fork-knife", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Транспарт", Icon: "bus", Type: domain.CategoryTypeExpense, Color: "#8b5cf6"},
		{Name: "Жыллё", Icon: "house", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Здароўе", Icon: "first-aid", Type: domain.CategoryTypeExpense, Color: "#22c55e"},
		{Name: "Забавы", Icon: "film-slate", Type: domain.CategoryTypeBoth, Color: "#ec4899"},
		{Name: "Пакупкі", Icon: "shopping-bag", Type: domain.CategoryTypeExpense, Color: "#ef4444"},
		{Name: "Зарплата", Icon: "briefcase", Type: domain.CategoryTypeIncome, Color: "#10b981"},
		{Name: "Іншае", Icon: "tag", Type: domain.CategoryTypeBoth, Color: "#64748b"},
		{Name: "Зберажэнні", Icon: "piggy-bank", Type: domain.CategoryTypeSavings, Color: "#3b82f6"},
	},
	"kk": {
		{Name: "Тамақ", Icon: "fork-knife", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Көлік", Icon: "bus", Type: domain.CategoryTypeExpense, Color: "#8b5cf6"},
		{Name: "Тұрғын үй", Icon: "house", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Денсаулық", Icon: "first-aid", Type: domain.CategoryTypeExpense, Color: "#22c55e"},
		{Name: "Ойын-сауық", Icon: "film-slate", Type: domain.CategoryTypeBoth, Color: "#ec4899"},
		{Name: "Сатып алу", Icon: "shopping-bag", Type: domain.CategoryTypeExpense, Color: "#ef4444"},
		{Name: "Жалақы", Icon: "briefcase", Type: domain.CategoryTypeIncome, Color: "#10b981"},
		{Name: "Басқа", Icon: "tag", Type: domain.CategoryTypeBoth, Color: "#64748b"},
		{Name: "Жинақтар", Icon: "piggy-bank", Type: domain.CategoryTypeSavings, Color: "#3b82f6"},
	},
	"uz": {
		{Name: "Ovqat", Icon: "fork-knife", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Transport", Icon: "bus", Type: domain.CategoryTypeExpense, Color: "#8b5cf6"},
		{Name: "Uy-joy", Icon: "house", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Salomatlik", Icon: "first-aid", Type: domain.CategoryTypeExpense, Color: "#22c55e"},
		{Name: "Ko'ngil ochar", Icon: "film-slate", Type: domain.CategoryTypeBoth, Color: "#ec4899"},
		{Name: "Xarid", Icon: "shopping-bag", Type: domain.CategoryTypeExpense, Color: "#ef4444"},
		{Name: "Maosh", Icon: "briefcase", Type: domain.CategoryTypeIncome, Color: "#10b981"},
		{Name: "Boshqa", Icon: "tag", Type: domain.CategoryTypeBoth, Color: "#64748b"},
		{Name: "Jamg'arma", Icon: "piggy-bank", Type: domain.CategoryTypeSavings, Color: "#3b82f6"},
	},
	"es": {
		{Name: "Comida", Icon: "fork-knife", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Transporte", Icon: "bus", Type: domain.CategoryTypeExpense, Color: "#8b5cf6"},
		{Name: "Vivienda", Icon: "house", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Salud", Icon: "first-aid", Type: domain.CategoryTypeExpense, Color: "#22c55e"},
		{Name: "Entretenimiento", Icon: "film-slate", Type: domain.CategoryTypeBoth, Color: "#ec4899"},
		{Name: "Compras", Icon: "shopping-bag", Type: domain.CategoryTypeExpense, Color: "#ef4444"},
		{Name: "Salario", Icon: "briefcase", Type: domain.CategoryTypeIncome, Color: "#10b981"},
		{Name: "Otros", Icon: "tag", Type: domain.CategoryTypeBoth, Color: "#64748b"},
		{Name: "Ahorros", Icon: "piggy-bank", Type: domain.CategoryTypeSavings, Color: "#3b82f6"},
	},
	"de": {
		{Name: "Essen", Icon: "fork-knife", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Transport", Icon: "bus", Type: domain.CategoryTypeExpense, Color: "#8b5cf6"},
		{Name: "Wohnen", Icon: "house", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Gesundheit", Icon: "first-aid", Type: domain.CategoryTypeExpense, Color: "#22c55e"},
		{Name: "Unterhaltung", Icon: "film-slate", Type: domain.CategoryTypeBoth, Color: "#ec4899"},
		{Name: "Einkaufen", Icon: "shopping-bag", Type: domain.CategoryTypeExpense, Color: "#ef4444"},
		{Name: "Gehalt", Icon: "briefcase", Type: domain.CategoryTypeIncome, Color: "#10b981"},
		{Name: "Sonstiges", Icon: "tag", Type: domain.CategoryTypeBoth, Color: "#64748b"},
		{Name: "Ersparnisse", Icon: "piggy-bank", Type: domain.CategoryTypeSavings, Color: "#3b82f6"},
	},
	"it": {
		{Name: "Cibo", Icon: "fork-knife", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Trasporto", Icon: "bus", Type: domain.CategoryTypeExpense, Color: "#8b5cf6"},
		{Name: "Casa", Icon: "house", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Salute", Icon: "first-aid", Type: domain.CategoryTypeExpense, Color: "#22c55e"},
		{Name: "Intrattenimento", Icon: "film-slate", Type: domain.CategoryTypeBoth, Color: "#ec4899"},
		{Name: "Shopping", Icon: "shopping-bag", Type: domain.CategoryTypeExpense, Color: "#ef4444"},
		{Name: "Stipendio", Icon: "briefcase", Type: domain.CategoryTypeIncome, Color: "#10b981"},
		{Name: "Altro", Icon: "tag", Type: domain.CategoryTypeBoth, Color: "#64748b"},
		{Name: "Risparmi", Icon: "piggy-bank", Type: domain.CategoryTypeSavings, Color: "#3b82f6"},
	},
	"fr": {
		{Name: "Nourriture", Icon: "fork-knife", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Transport", Icon: "bus", Type: domain.CategoryTypeExpense, Color: "#8b5cf6"},
		{Name: "Logement", Icon: "house", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Santé", Icon: "first-aid", Type: domain.CategoryTypeExpense, Color: "#22c55e"},
		{Name: "Divertissement", Icon: "film-slate", Type: domain.CategoryTypeBoth, Color: "#ec4899"},
		{Name: "Shopping", Icon: "shopping-bag", Type: domain.CategoryTypeExpense, Color: "#ef4444"},
		{Name: "Salaire", Icon: "briefcase", Type: domain.CategoryTypeIncome, Color: "#10b981"},
		{Name: "Autre", Icon: "tag", Type: domain.CategoryTypeBoth, Color: "#64748b"},
		{Name: "Épargne", Icon: "piggy-bank", Type: domain.CategoryTypeSavings, Color: "#3b82f6"},
	},
	"pt": {
		{Name: "Comida", Icon: "fork-knife", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Transporte", Icon: "bus", Type: domain.CategoryTypeExpense, Color: "#8b5cf6"},
		{Name: "Moradia", Icon: "house", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Saúde", Icon: "first-aid", Type: domain.CategoryTypeExpense, Color: "#22c55e"},
		{Name: "Entretenimento", Icon: "film-slate", Type: domain.CategoryTypeBoth, Color: "#ec4899"},
		{Name: "Compras", Icon: "shopping-bag", Type: domain.CategoryTypeExpense, Color: "#ef4444"},
		{Name: "Salário", Icon: "briefcase", Type: domain.CategoryTypeIncome, Color: "#10b981"},
		{Name: "Outros", Icon: "tag", Type: domain.CategoryTypeBoth, Color: "#64748b"},
		{Name: "Poupança", Icon: "piggy-bank", Type: domain.CategoryTypeSavings, Color: "#3b82f6"},
	},
	"nl": {
		{Name: "Eten", Icon: "fork-knife", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Vervoer", Icon: "bus", Type: domain.CategoryTypeExpense, Color: "#8b5cf6"},
		{Name: "Wonen", Icon: "house", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Gezondheid", Icon: "first-aid", Type: domain.CategoryTypeExpense, Color: "#22c55e"},
		{Name: "Entertainment", Icon: "film-slate", Type: domain.CategoryTypeBoth, Color: "#ec4899"},
		{Name: "Winkelen", Icon: "shopping-bag", Type: domain.CategoryTypeExpense, Color: "#ef4444"},
		{Name: "Salaris", Icon: "briefcase", Type: domain.CategoryTypeIncome, Color: "#10b981"},
		{Name: "Overig", Icon: "tag", Type: domain.CategoryTypeBoth, Color: "#64748b"},
		{Name: "Spaargeld", Icon: "piggy-bank", Type: domain.CategoryTypeSavings, Color: "#3b82f6"},
	},
	"ar": {
		{Name: "طعام", Icon: "fork-knife", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "مواصلات", Icon: "bus", Type: domain.CategoryTypeExpense, Color: "#8b5cf6"},
		{Name: "سكن", Icon: "house", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "صحة", Icon: "first-aid", Type: domain.CategoryTypeExpense, Color: "#22c55e"},
		{Name: "ترفيه", Icon: "film-slate", Type: domain.CategoryTypeBoth, Color: "#ec4899"},
		{Name: "تسوق", Icon: "shopping-bag", Type: domain.CategoryTypeExpense, Color: "#ef4444"},
		{Name: "راتب", Icon: "briefcase", Type: domain.CategoryTypeIncome, Color: "#10b981"},
		{Name: "أخرى", Icon: "tag", Type: domain.CategoryTypeBoth, Color: "#64748b"},
		{Name: "مدخرات", Icon: "piggy-bank", Type: domain.CategoryTypeSavings, Color: "#3b82f6"},
	},
	"tr": {
		{Name: "Yemek", Icon: "fork-knife", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Ulaşım", Icon: "bus", Type: domain.CategoryTypeExpense, Color: "#8b5cf6"},
		{Name: "Konut", Icon: "house", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Sağlık", Icon: "first-aid", Type: domain.CategoryTypeExpense, Color: "#22c55e"},
		{Name: "Eğlence", Icon: "film-slate", Type: domain.CategoryTypeBoth, Color: "#ec4899"},
		{Name: "Alışveriş", Icon: "shopping-bag", Type: domain.CategoryTypeExpense, Color: "#ef4444"},
		{Name: "Maaş", Icon: "briefcase", Type: domain.CategoryTypeIncome, Color: "#10b981"},
		{Name: "Diğer", Icon: "tag", Type: domain.CategoryTypeBoth, Color: "#64748b"},
		{Name: "Tasarruf", Icon: "piggy-bank", Type: domain.CategoryTypeSavings, Color: "#3b82f6"},
	},
	"ko": {
		{Name: "음식", Icon: "fork-knife", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "교통", Icon: "bus", Type: domain.CategoryTypeExpense, Color: "#8b5cf6"},
		{Name: "주거", Icon: "house", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "건강", Icon: "first-aid", Type: domain.CategoryTypeExpense, Color: "#22c55e"},
		{Name: "엔터테인먼트", Icon: "film-slate", Type: domain.CategoryTypeBoth, Color: "#ec4899"},
		{Name: "쇼핑", Icon: "shopping-bag", Type: domain.CategoryTypeExpense, Color: "#ef4444"},
		{Name: "급여", Icon: "briefcase", Type: domain.CategoryTypeIncome, Color: "#10b981"},
		{Name: "기타", Icon: "tag", Type: domain.CategoryTypeBoth, Color: "#64748b"},
		{Name: "저축", Icon: "piggy-bank", Type: domain.CategoryTypeSavings, Color: "#3b82f6"},
	},
	"ms": {
		{Name: "Makanan", Icon: "fork-knife", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Pengangkutan", Icon: "bus", Type: domain.CategoryTypeExpense, Color: "#8b5cf6"},
		{Name: "Perumahan", Icon: "house", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Kesihatan", Icon: "first-aid", Type: domain.CategoryTypeExpense, Color: "#22c55e"},
		{Name: "Hiburan", Icon: "film-slate", Type: domain.CategoryTypeBoth, Color: "#ec4899"},
		{Name: "Membeli-belah", Icon: "shopping-bag", Type: domain.CategoryTypeExpense, Color: "#ef4444"},
		{Name: "Gaji", Icon: "briefcase", Type: domain.CategoryTypeIncome, Color: "#10b981"},
		{Name: "Lain-lain", Icon: "tag", Type: domain.CategoryTypeBoth, Color: "#64748b"},
		{Name: "Simpanan", Icon: "piggy-bank", Type: domain.CategoryTypeSavings, Color: "#3b82f6"},
	},
	"id": {
		{Name: "Makanan", Icon: "fork-knife", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Transportasi", Icon: "bus", Type: domain.CategoryTypeExpense, Color: "#8b5cf6"},
		{Name: "Perumahan", Icon: "house", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Kesehatan", Icon: "first-aid", Type: domain.CategoryTypeExpense, Color: "#22c55e"},
		{Name: "Hiburan", Icon: "film-slate", Type: domain.CategoryTypeBoth, Color: "#ec4899"},
		{Name: "Belanja", Icon: "shopping-bag", Type: domain.CategoryTypeExpense, Color: "#ef4444"},
		{Name: "Gaji", Icon: "briefcase", Type: domain.CategoryTypeIncome, Color: "#10b981"},
		{Name: "Lainnya", Icon: "tag", Type: domain.CategoryTypeBoth, Color: "#64748b"},
		{Name: "Tabungan", Icon: "piggy-bank", Type: domain.CategoryTypeSavings, Color: "#3b82f6"},
	},
}

// defaultCategoriesFor returns the localized category seeds for the given language code.
// Falls back to English if the language code is not recognized.
func defaultCategoriesFor(lang string) []domain.CategorySeed {
	if cats, ok := localizedCategories[lang]; ok {
		return cats
	}
	return localizedCategories["en"]
}
