package api

import "github.com/horexdev/money-tracker/internal/domain"

// localizedCategories holds default category seeds for each supported locale.
// Each locale gets 9 categories: Food, Transport, Housing, Health, Entertainment,
// Shopping, Salary, Other, Savings.
var localizedCategories = map[string][]domain.CategorySeed{
	"en": {
		{Name: "Food", Emoji: "🍔", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Transport", Emoji: "🚌", Type: domain.CategoryTypeExpense, Color: "#8b5cf6"},
		{Name: "Housing", Emoji: "🏠", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Health", Emoji: "💊", Type: domain.CategoryTypeExpense, Color: "#22c55e"},
		{Name: "Entertainment", Emoji: "🎬", Type: domain.CategoryTypeBoth, Color: "#ec4899"},
		{Name: "Shopping", Emoji: "🛍", Type: domain.CategoryTypeExpense, Color: "#ef4444"},
		{Name: "Salary", Emoji: "💼", Type: domain.CategoryTypeIncome, Color: "#10b981"},
		{Name: "Other", Emoji: "📦", Type: domain.CategoryTypeBoth, Color: "#64748b"},
		{Name: "Savings", Emoji: "🏦", Type: domain.CategoryTypeSavings, Color: "#3b82f6"},
	},
	"ru": {
		{Name: "Еда", Emoji: "🍔", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Транспорт", Emoji: "🚌", Type: domain.CategoryTypeExpense, Color: "#8b5cf6"},
		{Name: "Жильё", Emoji: "🏠", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Здоровье", Emoji: "💊", Type: domain.CategoryTypeExpense, Color: "#22c55e"},
		{Name: "Развлечения", Emoji: "🎬", Type: domain.CategoryTypeBoth, Color: "#ec4899"},
		{Name: "Покупки", Emoji: "🛍", Type: domain.CategoryTypeExpense, Color: "#ef4444"},
		{Name: "Зарплата", Emoji: "💼", Type: domain.CategoryTypeIncome, Color: "#10b981"},
		{Name: "Другое", Emoji: "📦", Type: domain.CategoryTypeBoth, Color: "#64748b"},
		{Name: "Накопления", Emoji: "🏦", Type: domain.CategoryTypeSavings, Color: "#3b82f6"},
	},
	"uk": {
		{Name: "Їжа", Emoji: "🍔", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Транспорт", Emoji: "🚌", Type: domain.CategoryTypeExpense, Color: "#8b5cf6"},
		{Name: "Житло", Emoji: "🏠", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Здоров'я", Emoji: "💊", Type: domain.CategoryTypeExpense, Color: "#22c55e"},
		{Name: "Розваги", Emoji: "🎬", Type: domain.CategoryTypeBoth, Color: "#ec4899"},
		{Name: "Покупки", Emoji: "🛍", Type: domain.CategoryTypeExpense, Color: "#ef4444"},
		{Name: "Зарплата", Emoji: "💼", Type: domain.CategoryTypeIncome, Color: "#10b981"},
		{Name: "Інше", Emoji: "📦", Type: domain.CategoryTypeBoth, Color: "#64748b"},
		{Name: "Заощадження", Emoji: "🏦", Type: domain.CategoryTypeSavings, Color: "#3b82f6"},
	},
	"be": {
		{Name: "Ежа", Emoji: "🍔", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Транспарт", Emoji: "🚌", Type: domain.CategoryTypeExpense, Color: "#8b5cf6"},
		{Name: "Жыллё", Emoji: "🏠", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Здароўе", Emoji: "💊", Type: domain.CategoryTypeExpense, Color: "#22c55e"},
		{Name: "Забавы", Emoji: "🎬", Type: domain.CategoryTypeBoth, Color: "#ec4899"},
		{Name: "Пакупкі", Emoji: "🛍", Type: domain.CategoryTypeExpense, Color: "#ef4444"},
		{Name: "Зарплата", Emoji: "💼", Type: domain.CategoryTypeIncome, Color: "#10b981"},
		{Name: "Іншае", Emoji: "📦", Type: domain.CategoryTypeBoth, Color: "#64748b"},
		{Name: "Зберажэнні", Emoji: "🏦", Type: domain.CategoryTypeSavings, Color: "#3b82f6"},
	},
	"kk": {
		{Name: "Тамақ", Emoji: "🍔", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Көлік", Emoji: "🚌", Type: domain.CategoryTypeExpense, Color: "#8b5cf6"},
		{Name: "Тұрғын үй", Emoji: "🏠", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Денсаулық", Emoji: "💊", Type: domain.CategoryTypeExpense, Color: "#22c55e"},
		{Name: "Ойын-сауық", Emoji: "🎬", Type: domain.CategoryTypeBoth, Color: "#ec4899"},
		{Name: "Сатып алу", Emoji: "🛍", Type: domain.CategoryTypeExpense, Color: "#ef4444"},
		{Name: "Жалақы", Emoji: "💼", Type: domain.CategoryTypeIncome, Color: "#10b981"},
		{Name: "Басқа", Emoji: "📦", Type: domain.CategoryTypeBoth, Color: "#64748b"},
		{Name: "Жинақтар", Emoji: "🏦", Type: domain.CategoryTypeSavings, Color: "#3b82f6"},
	},
	"uz": {
		{Name: "Ovqat", Emoji: "🍔", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Transport", Emoji: "🚌", Type: domain.CategoryTypeExpense, Color: "#8b5cf6"},
		{Name: "Uy-joy", Emoji: "🏠", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Salomatlik", Emoji: "💊", Type: domain.CategoryTypeExpense, Color: "#22c55e"},
		{Name: "Ko'ngil ochar", Emoji: "🎬", Type: domain.CategoryTypeBoth, Color: "#ec4899"},
		{Name: "Xarid", Emoji: "🛍", Type: domain.CategoryTypeExpense, Color: "#ef4444"},
		{Name: "Maosh", Emoji: "💼", Type: domain.CategoryTypeIncome, Color: "#10b981"},
		{Name: "Boshqa", Emoji: "📦", Type: domain.CategoryTypeBoth, Color: "#64748b"},
		{Name: "Jamg'arma", Emoji: "🏦", Type: domain.CategoryTypeSavings, Color: "#3b82f6"},
	},
	"es": {
		{Name: "Comida", Emoji: "🍔", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Transporte", Emoji: "🚌", Type: domain.CategoryTypeExpense, Color: "#8b5cf6"},
		{Name: "Vivienda", Emoji: "🏠", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Salud", Emoji: "💊", Type: domain.CategoryTypeExpense, Color: "#22c55e"},
		{Name: "Entretenimiento", Emoji: "🎬", Type: domain.CategoryTypeBoth, Color: "#ec4899"},
		{Name: "Compras", Emoji: "🛍", Type: domain.CategoryTypeExpense, Color: "#ef4444"},
		{Name: "Salario", Emoji: "💼", Type: domain.CategoryTypeIncome, Color: "#10b981"},
		{Name: "Otros", Emoji: "📦", Type: domain.CategoryTypeBoth, Color: "#64748b"},
		{Name: "Ahorros", Emoji: "🏦", Type: domain.CategoryTypeSavings, Color: "#3b82f6"},
	},
	"de": {
		{Name: "Essen", Emoji: "🍔", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Transport", Emoji: "🚌", Type: domain.CategoryTypeExpense, Color: "#8b5cf6"},
		{Name: "Wohnen", Emoji: "🏠", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Gesundheit", Emoji: "💊", Type: domain.CategoryTypeExpense, Color: "#22c55e"},
		{Name: "Unterhaltung", Emoji: "🎬", Type: domain.CategoryTypeBoth, Color: "#ec4899"},
		{Name: "Einkaufen", Emoji: "🛍", Type: domain.CategoryTypeExpense, Color: "#ef4444"},
		{Name: "Gehalt", Emoji: "💼", Type: domain.CategoryTypeIncome, Color: "#10b981"},
		{Name: "Sonstiges", Emoji: "📦", Type: domain.CategoryTypeBoth, Color: "#64748b"},
		{Name: "Ersparnisse", Emoji: "🏦", Type: domain.CategoryTypeSavings, Color: "#3b82f6"},
	},
	"it": {
		{Name: "Cibo", Emoji: "🍔", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Trasporto", Emoji: "🚌", Type: domain.CategoryTypeExpense, Color: "#8b5cf6"},
		{Name: "Casa", Emoji: "🏠", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Salute", Emoji: "💊", Type: domain.CategoryTypeExpense, Color: "#22c55e"},
		{Name: "Intrattenimento", Emoji: "🎬", Type: domain.CategoryTypeBoth, Color: "#ec4899"},
		{Name: "Shopping", Emoji: "🛍", Type: domain.CategoryTypeExpense, Color: "#ef4444"},
		{Name: "Stipendio", Emoji: "💼", Type: domain.CategoryTypeIncome, Color: "#10b981"},
		{Name: "Altro", Emoji: "📦", Type: domain.CategoryTypeBoth, Color: "#64748b"},
		{Name: "Risparmi", Emoji: "🏦", Type: domain.CategoryTypeSavings, Color: "#3b82f6"},
	},
	"fr": {
		{Name: "Nourriture", Emoji: "🍔", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Transport", Emoji: "🚌", Type: domain.CategoryTypeExpense, Color: "#8b5cf6"},
		{Name: "Logement", Emoji: "🏠", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Santé", Emoji: "💊", Type: domain.CategoryTypeExpense, Color: "#22c55e"},
		{Name: "Divertissement", Emoji: "🎬", Type: domain.CategoryTypeBoth, Color: "#ec4899"},
		{Name: "Shopping", Emoji: "🛍", Type: domain.CategoryTypeExpense, Color: "#ef4444"},
		{Name: "Salaire", Emoji: "💼", Type: domain.CategoryTypeIncome, Color: "#10b981"},
		{Name: "Autre", Emoji: "📦", Type: domain.CategoryTypeBoth, Color: "#64748b"},
		{Name: "Épargne", Emoji: "🏦", Type: domain.CategoryTypeSavings, Color: "#3b82f6"},
	},
	"pt": {
		{Name: "Comida", Emoji: "🍔", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Transporte", Emoji: "🚌", Type: domain.CategoryTypeExpense, Color: "#8b5cf6"},
		{Name: "Moradia", Emoji: "🏠", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Saúde", Emoji: "💊", Type: domain.CategoryTypeExpense, Color: "#22c55e"},
		{Name: "Entretenimento", Emoji: "🎬", Type: domain.CategoryTypeBoth, Color: "#ec4899"},
		{Name: "Compras", Emoji: "🛍", Type: domain.CategoryTypeExpense, Color: "#ef4444"},
		{Name: "Salário", Emoji: "💼", Type: domain.CategoryTypeIncome, Color: "#10b981"},
		{Name: "Outros", Emoji: "📦", Type: domain.CategoryTypeBoth, Color: "#64748b"},
		{Name: "Poupança", Emoji: "🏦", Type: domain.CategoryTypeSavings, Color: "#3b82f6"},
	},
	"nl": {
		{Name: "Eten", Emoji: "🍔", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Vervoer", Emoji: "🚌", Type: domain.CategoryTypeExpense, Color: "#8b5cf6"},
		{Name: "Wonen", Emoji: "🏠", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Gezondheid", Emoji: "💊", Type: domain.CategoryTypeExpense, Color: "#22c55e"},
		{Name: "Entertainment", Emoji: "🎬", Type: domain.CategoryTypeBoth, Color: "#ec4899"},
		{Name: "Winkelen", Emoji: "🛍", Type: domain.CategoryTypeExpense, Color: "#ef4444"},
		{Name: "Salaris", Emoji: "💼", Type: domain.CategoryTypeIncome, Color: "#10b981"},
		{Name: "Overig", Emoji: "📦", Type: domain.CategoryTypeBoth, Color: "#64748b"},
		{Name: "Spaargeld", Emoji: "🏦", Type: domain.CategoryTypeSavings, Color: "#3b82f6"},
	},
	"ar": {
		{Name: "طعام", Emoji: "🍔", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "مواصلات", Emoji: "🚌", Type: domain.CategoryTypeExpense, Color: "#8b5cf6"},
		{Name: "سكن", Emoji: "🏠", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "صحة", Emoji: "💊", Type: domain.CategoryTypeExpense, Color: "#22c55e"},
		{Name: "ترفيه", Emoji: "🎬", Type: domain.CategoryTypeBoth, Color: "#ec4899"},
		{Name: "تسوق", Emoji: "🛍", Type: domain.CategoryTypeExpense, Color: "#ef4444"},
		{Name: "راتب", Emoji: "💼", Type: domain.CategoryTypeIncome, Color: "#10b981"},
		{Name: "أخرى", Emoji: "📦", Type: domain.CategoryTypeBoth, Color: "#64748b"},
		{Name: "مدخرات", Emoji: "🏦", Type: domain.CategoryTypeSavings, Color: "#3b82f6"},
	},
	"tr": {
		{Name: "Yemek", Emoji: "🍔", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Ulaşım", Emoji: "🚌", Type: domain.CategoryTypeExpense, Color: "#8b5cf6"},
		{Name: "Konut", Emoji: "🏠", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Sağlık", Emoji: "💊", Type: domain.CategoryTypeExpense, Color: "#22c55e"},
		{Name: "Eğlence", Emoji: "🎬", Type: domain.CategoryTypeBoth, Color: "#ec4899"},
		{Name: "Alışveriş", Emoji: "🛍", Type: domain.CategoryTypeExpense, Color: "#ef4444"},
		{Name: "Maaş", Emoji: "💼", Type: domain.CategoryTypeIncome, Color: "#10b981"},
		{Name: "Diğer", Emoji: "📦", Type: domain.CategoryTypeBoth, Color: "#64748b"},
		{Name: "Tasarruf", Emoji: "🏦", Type: domain.CategoryTypeSavings, Color: "#3b82f6"},
	},
	"ko": {
		{Name: "음식", Emoji: "🍔", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "교통", Emoji: "🚌", Type: domain.CategoryTypeExpense, Color: "#8b5cf6"},
		{Name: "주거", Emoji: "🏠", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "건강", Emoji: "💊", Type: domain.CategoryTypeExpense, Color: "#22c55e"},
		{Name: "엔터테인먼트", Emoji: "🎬", Type: domain.CategoryTypeBoth, Color: "#ec4899"},
		{Name: "쇼핑", Emoji: "🛍", Type: domain.CategoryTypeExpense, Color: "#ef4444"},
		{Name: "급여", Emoji: "💼", Type: domain.CategoryTypeIncome, Color: "#10b981"},
		{Name: "기타", Emoji: "📦", Type: domain.CategoryTypeBoth, Color: "#64748b"},
		{Name: "저축", Emoji: "🏦", Type: domain.CategoryTypeSavings, Color: "#3b82f6"},
	},
	"ms": {
		{Name: "Makanan", Emoji: "🍔", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Pengangkutan", Emoji: "🚌", Type: domain.CategoryTypeExpense, Color: "#8b5cf6"},
		{Name: "Perumahan", Emoji: "🏠", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Kesihatan", Emoji: "💊", Type: domain.CategoryTypeExpense, Color: "#22c55e"},
		{Name: "Hiburan", Emoji: "🎬", Type: domain.CategoryTypeBoth, Color: "#ec4899"},
		{Name: "Membeli-belah", Emoji: "🛍", Type: domain.CategoryTypeExpense, Color: "#ef4444"},
		{Name: "Gaji", Emoji: "💼", Type: domain.CategoryTypeIncome, Color: "#10b981"},
		{Name: "Lain-lain", Emoji: "📦", Type: domain.CategoryTypeBoth, Color: "#64748b"},
		{Name: "Simpanan", Emoji: "🏦", Type: domain.CategoryTypeSavings, Color: "#3b82f6"},
	},
	"id": {
		{Name: "Makanan", Emoji: "🍔", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Transportasi", Emoji: "🚌", Type: domain.CategoryTypeExpense, Color: "#8b5cf6"},
		{Name: "Perumahan", Emoji: "🏠", Type: domain.CategoryTypeExpense, Color: "#f97316"},
		{Name: "Kesehatan", Emoji: "💊", Type: domain.CategoryTypeExpense, Color: "#22c55e"},
		{Name: "Hiburan", Emoji: "🎬", Type: domain.CategoryTypeBoth, Color: "#ec4899"},
		{Name: "Belanja", Emoji: "🛍", Type: domain.CategoryTypeExpense, Color: "#ef4444"},
		{Name: "Gaji", Emoji: "💼", Type: domain.CategoryTypeIncome, Color: "#10b981"},
		{Name: "Lainnya", Emoji: "📦", Type: domain.CategoryTypeBoth, Color: "#64748b"},
		{Name: "Tabungan", Emoji: "🏦", Type: domain.CategoryTypeSavings, Color: "#3b82f6"},
	},
}

// defaultCategoriesFor returns the localized category seeds for the given language code.
// Falls back to English if the language code is not recognized.
func defaultCategoriesFor(lang string) []domain.CategorySeed {
	if cats, ok := localizedCategories[lang]; ok {
		return cats
	}
	return localizedCategories["en"]
}
