// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearDefaultAccounts = `-- name: ClearDefaultAccounts :exec
UPDATE accounts SET is_default = false
WHERE user_id = $1 AND is_default = true
`

func (q *Queries) ClearDefaultAccounts(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, clearDefaultAccounts, userID)
	return err
}

const countAccountTransactions = `-- name: CountAccountTransactions :one
SELECT COUNT(*)::BIGINT FROM transactions
WHERE account_id = $1 AND user_id = $2
`

type CountAccountTransactionsParams struct {
	AccountID pgtype.Int8 `json:"account_id"`
	UserID    int64       `json:"user_id"`
}

func (q *Queries) CountAccountTransactions(ctx context.Context, arg CountAccountTransactionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAccountTransactions, arg.AccountID, arg.UserID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (user_id, name, icon, color, type, currency_code, is_default, include_in_total)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, name, icon, color, type, currency_code, is_default, include_in_total, created_at, updated_at
`

type CreateAccountParams struct {
	UserID         int64       `json:"user_id"`
	Name           string      `json:"name"`
	Icon           string      `json:"icon"`
	Color          string      `json:"color"`
	Type           AccountType `json:"type"`
	CurrencyCode   string      `json:"currency_code"`
	IsDefault      bool        `json:"is_default"`
	IncludeInTotal bool        `json:"include_in_total"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.UserID,
		arg.Name,
		arg.Icon,
		arg.Color,
		arg.Type,
		arg.CurrencyCode,
		arg.IsDefault,
		arg.IncludeInTotal,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Icon,
		&i.Color,
		&i.Type,
		&i.CurrencyCode,
		&i.IsDefault,
		&i.IncludeInTotal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts WHERE id = $1 AND user_id = $2
`

type DeleteAccountParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteAccount(ctx context.Context, arg DeleteAccountParams) error {
	_, err := q.db.Exec(ctx, deleteAccount, arg.ID, arg.UserID)
	return err
}

const getAccountBalance = `-- name: GetAccountBalance :one
SELECT COALESCE(
    SUM(CASE WHEN type = 'income' THEN amount_cents ELSE -amount_cents END), 0
)::BIGINT AS balance_cents
FROM transactions
WHERE account_id = $1
  AND user_id    = $2
  AND type IN ('income', 'expense')
`

type GetAccountBalanceParams struct {
	AccountID pgtype.Int8 `json:"account_id"`
	UserID    int64       `json:"user_id"`
}

func (q *Queries) GetAccountBalance(ctx context.Context, arg GetAccountBalanceParams) (int64, error) {
	row := q.db.QueryRow(ctx, getAccountBalance, arg.AccountID, arg.UserID)
	var balance_cents int64
	err := row.Scan(&balance_cents)
	return balance_cents, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, user_id, name, icon, color, type, currency_code, is_default, include_in_total, created_at, updated_at FROM accounts
WHERE id = $1 AND user_id = $2
`

type GetAccountByIDParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetAccountByID(ctx context.Context, arg GetAccountByIDParams) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, arg.ID, arg.UserID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Icon,
		&i.Color,
		&i.Type,
		&i.CurrencyCode,
		&i.IsDefault,
		&i.IncludeInTotal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDefaultAccount = `-- name: GetDefaultAccount :one
SELECT id, user_id, name, icon, color, type, currency_code, is_default, include_in_total, created_at, updated_at FROM accounts
WHERE user_id = $1 AND is_default = true
LIMIT 1
`

func (q *Queries) GetDefaultAccount(ctx context.Context, userID int64) (Account, error) {
	row := q.db.QueryRow(ctx, getDefaultAccount, userID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Icon,
		&i.Color,
		&i.Type,
		&i.CurrencyCode,
		&i.IsDefault,
		&i.IncludeInTotal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccountsByUser = `-- name: ListAccountsByUser :many
SELECT id, user_id, name, icon, color, type, currency_code, is_default, include_in_total, created_at, updated_at FROM accounts
WHERE user_id = $1
ORDER BY is_default DESC, created_at ASC
`

func (q *Queries) ListAccountsByUser(ctx context.Context, userID int64) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccountsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Icon,
			&i.Color,
			&i.Type,
			&i.CurrencyCode,
			&i.IsDefault,
			&i.IncludeInTotal,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAccountDefault = `-- name: SetAccountDefault :one
UPDATE accounts SET is_default = true, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, icon, color, type, currency_code, is_default, include_in_total, created_at, updated_at
`

type SetAccountDefaultParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) SetAccountDefault(ctx context.Context, arg SetAccountDefaultParams) (Account, error) {
	row := q.db.QueryRow(ctx, setAccountDefault, arg.ID, arg.UserID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Icon,
		&i.Color,
		&i.Type,
		&i.CurrencyCode,
		&i.IsDefault,
		&i.IncludeInTotal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts
SET name             = $3,
    icon             = $4,
    color            = $5,
    type             = $6,
    currency_code    = $7,
    include_in_total = $8,
    updated_at       = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, icon, color, type, currency_code, is_default, include_in_total, created_at, updated_at
`

type UpdateAccountParams struct {
	ID             int64       `json:"id"`
	UserID         int64       `json:"user_id"`
	Name           string      `json:"name"`
	Icon           string      `json:"icon"`
	Color          string      `json:"color"`
	Type           AccountType `json:"type"`
	CurrencyCode   string      `json:"currency_code"`
	IncludeInTotal bool        `json:"include_in_total"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccount,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Icon,
		arg.Color,
		arg.Type,
		arg.CurrencyCode,
		arg.IncludeInTotal,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Icon,
		&i.Color,
		&i.Type,
		&i.CurrencyCode,
		&i.IsDefault,
		&i.IncludeInTotal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
