// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveUsersInPeriod = `-- name: CountActiveUsersInPeriod :one
SELECT count(DISTINCT user_id)::BIGINT FROM transactions WHERE created_at >= $1 AND created_at < $2
`

type CountActiveUsersInPeriodParams struct {
	FromTs pgtype.Timestamptz `json:"from_ts"`
	ToTs   pgtype.Timestamptz `json:"to_ts"`
}

func (q *Queries) CountActiveUsersInPeriod(ctx context.Context, arg CountActiveUsersInPeriodParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveUsersInPeriod, arg.FromTs, arg.ToTs)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countAllUsers = `-- name: CountAllUsers :one
SELECT count(*)::BIGINT FROM users
`

func (q *Queries) CountAllUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllUsers)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countNewUsers = `-- name: CountNewUsers :one
SELECT count(*)::BIGINT FROM users WHERE created_at >= $1 AND created_at < $2
`

type CountNewUsersParams struct {
	FromTs pgtype.Timestamptz `json:"from_ts"`
	ToTs   pgtype.Timestamptz `json:"to_ts"`
}

func (q *Queries) CountNewUsers(ctx context.Context, arg CountNewUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countNewUsers, arg.FromTs, arg.ToTs)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countRetainedUsers = `-- name: CountRetainedUsers :one
SELECT count(*)::BIGINT
FROM users u
WHERE u.created_at >= $1 AND u.created_at < $2
  AND EXISTS (
    SELECT 1 FROM transactions t
    WHERE t.user_id = u.id AND t.created_at >= $3 AND t.created_at < $4
  )
`

type CountRetainedUsersParams struct {
	SignupFrom pgtype.Timestamptz `json:"signup_from"`
	SignupTo   pgtype.Timestamptz `json:"signup_to"`
	ActiveFrom pgtype.Timestamptz `json:"active_from"`
	ActiveTo   pgtype.Timestamptz `json:"active_to"`
}

func (q *Queries) CountRetainedUsers(ctx context.Context, arg CountRetainedUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRetainedUsers,
		arg.SignupFrom,
		arg.SignupTo,
		arg.ActiveFrom,
		arg.ActiveTo,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listAllUserIDs = `-- name: ListAllUserIDs :many
SELECT id FROM users
`

func (q *Queries) ListAllUserIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, listAllUserIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllUsers = `-- name: ListAllUsers :many
SELECT id, username, first_name, last_name, created_at, updated_at, display_currencies, language, notify_budget_alerts, notify_recurring_reminders, notify_weekly_summary, notify_goal_milestones, theme, hide_amounts FROM users ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListAllUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAllUsers(ctx context.Context, arg ListAllUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listAllUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DisplayCurrencies,
			&i.Language,
			&i.NotifyBudgetAlerts,
			&i.NotifyRecurringReminders,
			&i.NotifyWeeklySummary,
			&i.NotifyGoalMilestones,
			&i.Theme,
			&i.HideAmounts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
