// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: budgets.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBudget = `-- name: CreateBudget :one
INSERT INTO budgets (user_id, category_id, limit_cents, period, currency_code, notify_at_percent, notifications_enabled)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, category_id, limit_cents, period, currency_code, notify_at_percent, created_at, updated_at, last_notified_at, notifications_enabled, last_notified_percent
`

type CreateBudgetParams struct {
	UserID               int64  `json:"user_id"`
	CategoryID           int64  `json:"category_id"`
	LimitCents           int64  `json:"limit_cents"`
	Period               string `json:"period"`
	CurrencyCode         string `json:"currency_code"`
	NotifyAtPercent      int32  `json:"notify_at_percent"`
	NotificationsEnabled bool   `json:"notifications_enabled"`
}

func (q *Queries) CreateBudget(ctx context.Context, arg CreateBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, createBudget,
		arg.UserID,
		arg.CategoryID,
		arg.LimitCents,
		arg.Period,
		arg.CurrencyCode,
		arg.NotifyAtPercent,
		arg.NotificationsEnabled,
	)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.LimitCents,
		&i.Period,
		&i.CurrencyCode,
		&i.NotifyAtPercent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastNotifiedAt,
		&i.NotificationsEnabled,
		&i.LastNotifiedPercent,
	)
	return i, err
}

const deleteBudget = `-- name: DeleteBudget :exec
DELETE FROM budgets WHERE id = $1 AND user_id = $2
`

type DeleteBudgetParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteBudget(ctx context.Context, arg DeleteBudgetParams) error {
	_, err := q.db.Exec(ctx, deleteBudget, arg.ID, arg.UserID)
	return err
}

const getBudgetByID = `-- name: GetBudgetByID :one
SELECT id, user_id, category_id, limit_cents, period, currency_code, notify_at_percent, created_at, updated_at, last_notified_at, notifications_enabled, last_notified_percent FROM budgets WHERE id = $1 AND user_id = $2
`

type GetBudgetByIDParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetBudgetByID(ctx context.Context, arg GetBudgetByIDParams) (Budget, error) {
	row := q.db.QueryRow(ctx, getBudgetByID, arg.ID, arg.UserID)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.LimitCents,
		&i.Period,
		&i.CurrencyCode,
		&i.NotifyAtPercent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastNotifiedAt,
		&i.NotificationsEnabled,
		&i.LastNotifiedPercent,
	)
	return i, err
}

const getBudgetByUserCategoryPeriod = `-- name: GetBudgetByUserCategoryPeriod :one
SELECT id, user_id, category_id, limit_cents, period, currency_code, notify_at_percent, created_at, updated_at, last_notified_at, notifications_enabled, last_notified_percent FROM budgets
WHERE user_id = $1 AND category_id = $2 AND period = $3
`

type GetBudgetByUserCategoryPeriodParams struct {
	UserID     int64  `json:"user_id"`
	CategoryID int64  `json:"category_id"`
	Period     string `json:"period"`
}

func (q *Queries) GetBudgetByUserCategoryPeriod(ctx context.Context, arg GetBudgetByUserCategoryPeriodParams) (Budget, error) {
	row := q.db.QueryRow(ctx, getBudgetByUserCategoryPeriod, arg.UserID, arg.CategoryID, arg.Period)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.LimitCents,
		&i.Period,
		&i.CurrencyCode,
		&i.NotifyAtPercent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastNotifiedAt,
		&i.NotificationsEnabled,
		&i.LastNotifiedPercent,
	)
	return i, err
}

const getSpentInPeriod = `-- name: GetSpentInPeriod :one
SELECT COALESCE(SUM(amount_cents), 0)::BIGINT AS total_spent
FROM transactions
WHERE user_id     = $1
  AND category_id = $2
  AND type         = 'expense'
  AND currency_code = $3
  AND created_at  >= $4
  AND created_at  <  $5
`

type GetSpentInPeriodParams struct {
	UserID       int64              `json:"user_id"`
	CategoryID   int64              `json:"category_id"`
	CurrencyCode string             `json:"currency_code"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2  pgtype.Timestamptz `json:"created_at_2"`
}

func (q *Queries) GetSpentInPeriod(ctx context.Context, arg GetSpentInPeriodParams) (int64, error) {
	row := q.db.QueryRow(ctx, getSpentInPeriod,
		arg.UserID,
		arg.CategoryID,
		arg.CurrencyCode,
		arg.CreatedAt,
		arg.CreatedAt_2,
	)
	var total_spent int64
	err := row.Scan(&total_spent)
	return total_spent, err
}

const listBudgetsByUser = `-- name: ListBudgetsByUser :many
SELECT
    b.id, b.user_id, b.category_id, b.limit_cents, b.period, b.currency_code, b.notify_at_percent, b.created_at, b.updated_at, b.last_notified_at, b.notifications_enabled, b.last_notified_percent,
    c.name  AS category_name,
    c.emoji AS category_emoji,
    c.color AS category_color
FROM budgets b
JOIN categories c ON c.id = b.category_id
WHERE b.user_id = $1
ORDER BY b.created_at DESC
`

type ListBudgetsByUserRow struct {
	ID                   int64              `json:"id"`
	UserID               int64              `json:"user_id"`
	CategoryID           int64              `json:"category_id"`
	LimitCents           int64              `json:"limit_cents"`
	Period               string             `json:"period"`
	CurrencyCode         string             `json:"currency_code"`
	NotifyAtPercent      int32              `json:"notify_at_percent"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	LastNotifiedAt       pgtype.Timestamptz `json:"last_notified_at"`
	NotificationsEnabled bool               `json:"notifications_enabled"`
	LastNotifiedPercent  int32              `json:"last_notified_percent"`
	CategoryName         string             `json:"category_name"`
	CategoryEmoji        string             `json:"category_emoji"`
	CategoryColor        string             `json:"category_color"`
}

func (q *Queries) ListBudgetsByUser(ctx context.Context, userID int64) ([]ListBudgetsByUserRow, error) {
	rows, err := q.db.Query(ctx, listBudgetsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBudgetsByUserRow{}
	for rows.Next() {
		var i ListBudgetsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.LimitCents,
			&i.Period,
			&i.CurrencyCode,
			&i.NotifyAtPercent,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastNotifiedAt,
			&i.NotificationsEnabled,
			&i.LastNotifiedPercent,
			&i.CategoryName,
			&i.CategoryEmoji,
			&i.CategoryColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctUsersWithBudgets = `-- name: ListDistinctUsersWithBudgets :many
SELECT DISTINCT user_id FROM budgets
`

func (q *Queries) ListDistinctUsersWithBudgets(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, listDistinctUsersWithBudgets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var user_id int64
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBudget = `-- name: UpdateBudget :one
UPDATE budgets
SET limit_cents             = $3,
    period                  = $4,
    currency_code           = $5,
    notify_at_percent       = $6,
    notifications_enabled   = $7,
    updated_at              = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, category_id, limit_cents, period, currency_code, notify_at_percent, created_at, updated_at, last_notified_at, notifications_enabled, last_notified_percent
`

type UpdateBudgetParams struct {
	ID                   int64  `json:"id"`
	UserID               int64  `json:"user_id"`
	LimitCents           int64  `json:"limit_cents"`
	Period               string `json:"period"`
	CurrencyCode         string `json:"currency_code"`
	NotifyAtPercent      int32  `json:"notify_at_percent"`
	NotificationsEnabled bool   `json:"notifications_enabled"`
}

func (q *Queries) UpdateBudget(ctx context.Context, arg UpdateBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, updateBudget,
		arg.ID,
		arg.UserID,
		arg.LimitCents,
		arg.Period,
		arg.CurrencyCode,
		arg.NotifyAtPercent,
		arg.NotificationsEnabled,
	)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.LimitCents,
		&i.Period,
		&i.CurrencyCode,
		&i.NotifyAtPercent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastNotifiedAt,
		&i.NotificationsEnabled,
		&i.LastNotifiedPercent,
	)
	return i, err
}

const updateBudgetLastNotified = `-- name: UpdateBudgetLastNotified :exec
UPDATE budgets
SET last_notified_at     = now(),
    last_notified_percent = $2
WHERE id = $1
`

type UpdateBudgetLastNotifiedParams struct {
	ID                  int64 `json:"id"`
	LastNotifiedPercent int32 `json:"last_notified_percent"`
}

func (q *Queries) UpdateBudgetLastNotified(ctx context.Context, arg UpdateBudgetLastNotifiedParams) error {
	_, err := q.db.Exec(ctx, updateBudgetLastNotified, arg.ID, arg.LastNotifiedPercent)
	return err
}
