// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exchange_snapshots.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getExchangeRate = `-- name: GetExchangeRate :one
SELECT rate
FROM exchange_rate_snapshots
WHERE snapshot_date = $1
  AND base_currency = $2
  AND target_currency = $3
`

type GetExchangeRateParams struct {
	SnapshotDate   pgtype.Date `json:"snapshot_date"`
	BaseCurrency   string      `json:"base_currency"`
	TargetCurrency string      `json:"target_currency"`
}

func (q *Queries) GetExchangeRate(ctx context.Context, arg GetExchangeRateParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getExchangeRate, arg.SnapshotDate, arg.BaseCurrency, arg.TargetCurrency)
	var rate pgtype.Numeric
	err := row.Scan(&rate)
	return rate, err
}

const getExchangeRateOrLatest = `-- name: GetExchangeRateOrLatest :one
SELECT rate
FROM exchange_rate_snapshots
WHERE base_currency = $1
  AND target_currency = $2
  AND snapshot_date <= $3
ORDER BY snapshot_date DESC
LIMIT 1
`

type GetExchangeRateOrLatestParams struct {
	BaseCurrency   string      `json:"base_currency"`
	TargetCurrency string      `json:"target_currency"`
	SnapshotDate   pgtype.Date `json:"snapshot_date"`
}

// Returns the rate for the exact date, or the most recent rate before that date.
func (q *Queries) GetExchangeRateOrLatest(ctx context.Context, arg GetExchangeRateOrLatestParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getExchangeRateOrLatest, arg.BaseCurrency, arg.TargetCurrency, arg.SnapshotDate)
	var rate pgtype.Numeric
	err := row.Scan(&rate)
	return rate, err
}

const getLatestSnapshotDate = `-- name: GetLatestSnapshotDate :one
SELECT COALESCE(MAX(snapshot_date), '1970-01-01'::DATE)::DATE AS latest_date
FROM exchange_rate_snapshots
`

func (q *Queries) GetLatestSnapshotDate(ctx context.Context) (pgtype.Date, error) {
	row := q.db.QueryRow(ctx, getLatestSnapshotDate)
	var latest_date pgtype.Date
	err := row.Scan(&latest_date)
	return latest_date, err
}

const listDistinctBaseCurrencies = `-- name: ListDistinctBaseCurrencies :many
SELECT DISTINCT currency_code
FROM accounts
`

// Returns all distinct base currencies used across accounts (for daily cron).
func (q *Queries) ListDistinctBaseCurrencies(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listDistinctBaseCurrencies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var currency_code string
		if err := rows.Scan(&currency_code); err != nil {
			return nil, err
		}
		items = append(items, currency_code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertExchangeRate = `-- name: UpsertExchangeRate :exec
INSERT INTO exchange_rate_snapshots (snapshot_date, base_currency, target_currency, rate)
VALUES ($1, $2, $3, $4)
ON CONFLICT (snapshot_date, base_currency, target_currency)
DO UPDATE SET rate = EXCLUDED.rate
`

type UpsertExchangeRateParams struct {
	SnapshotDate   pgtype.Date    `json:"snapshot_date"`
	BaseCurrency   string         `json:"base_currency"`
	TargetCurrency string         `json:"target_currency"`
	Rate           pgtype.Numeric `json:"rate"`
}

func (q *Queries) UpsertExchangeRate(ctx context.Context, arg UpsertExchangeRateParams) error {
	_, err := q.db.Exec(ctx, upsertExchangeRate,
		arg.SnapshotDate,
		arg.BaseCurrency,
		arg.TargetCurrency,
		arg.Rate,
	)
	return err
}
