// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: goal_transactions.sql

package sqlcgen

import (
	"context"
)

const insertGoalTransaction = `-- name: InsertGoalTransaction :exec
INSERT INTO goal_transactions (goal_id, user_id, type, amount_cents)
VALUES ($1, $2, $3, $4)
`

type InsertGoalTransactionParams struct {
	GoalID      int64  `json:"goal_id"`
	UserID      int64  `json:"user_id"`
	Type        string `json:"type"`
	AmountCents int64  `json:"amount_cents"`
}

func (q *Queries) InsertGoalTransaction(ctx context.Context, arg InsertGoalTransactionParams) error {
	_, err := q.db.Exec(ctx, insertGoalTransaction,
		arg.GoalID,
		arg.UserID,
		arg.Type,
		arg.AmountCents,
	)
	return err
}

const listGoalTransactions = `-- name: ListGoalTransactions :many
SELECT id, goal_id, user_id, type, amount_cents, created_at
FROM goal_transactions
WHERE goal_id = $1 AND user_id = $2
ORDER BY created_at DESC
`

type ListGoalTransactionsParams struct {
	GoalID int64 `json:"goal_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) ListGoalTransactions(ctx context.Context, arg ListGoalTransactionsParams) ([]GoalTransaction, error) {
	rows, err := q.db.Query(ctx, listGoalTransactions, arg.GoalID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GoalTransaction{}
	for rows.Next() {
		var i GoalTransaction
		if err := rows.Scan(
			&i.ID,
			&i.GoalID,
			&i.UserID,
			&i.Type,
			&i.AmountCents,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
