// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql/driver"
	"fmt"

	"github.com/horexdev/money-tracker/internal/domain"
	"github.com/jackc/pgx/v5/pgtype"
)

type TransactionType string

const (
	TransactionTypeExpense TransactionType = "expense"
	TransactionTypeIncome  TransactionType = "income"
)

func (e *TransactionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionType(s)
	case string:
		*e = TransactionType(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionType: %T", src)
	}
	return nil
}

type NullTransactionType struct {
	TransactionType TransactionType `json:"transaction_type"`
	Valid           bool            `json:"valid"` // Valid is true if TransactionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionType) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionType), nil
}

type Budget struct {
	ID              int64              `json:"id"`
	UserID          int64              `json:"user_id"`
	CategoryID      int64              `json:"category_id"`
	LimitCents      int64              `json:"limit_cents"`
	Period          string             `json:"period"`
	CurrencyCode    string             `json:"currency_code"`
	NotifyAtPercent int32              `json:"notify_at_percent"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Category struct {
	ID        int64              `json:"id"`
	UserID    pgtype.Int8        `json:"user_id"`
	Name      string             `json:"name"`
	Emoji     string             `json:"emoji"`
	Type      string             `json:"type"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type RecurringTransaction struct {
	ID           int64                  `json:"id"`
	UserID       int64                  `json:"user_id"`
	CategoryID   int64                  `json:"category_id"`
	Type         domain.TransactionType `json:"type"`
	AmountCents  int64                  `json:"amount_cents"`
	CurrencyCode string                 `json:"currency_code"`
	Note         string                 `json:"note"`
	Frequency    string                 `json:"frequency"`
	NextRunAt    pgtype.Timestamptz     `json:"next_run_at"`
	IsActive     bool                   `json:"is_active"`
	CreatedAt    pgtype.Timestamptz     `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz     `json:"updated_at"`
}

type SavingsGoal struct {
	ID           int64              `json:"id"`
	UserID       int64              `json:"user_id"`
	Name         string             `json:"name"`
	TargetCents  int64              `json:"target_cents"`
	CurrentCents int64              `json:"current_cents"`
	CurrencyCode string             `json:"currency_code"`
	Deadline     pgtype.Date        `json:"deadline"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Transaction struct {
	ID           int64                  `json:"id"`
	UserID       int64                  `json:"user_id"`
	Type         domain.TransactionType `json:"type"`
	AmountCents  int64                  `json:"amount_cents"`
	CategoryID   int64                  `json:"category_id"`
	Note         string                 `json:"note"`
	CreatedAt    pgtype.Timestamptz     `json:"created_at"`
	CurrencyCode string                 `json:"currency_code"`
}

type User struct {
	ID                int64              `json:"id"`
	Username          string             `json:"username"`
	FirstName         string             `json:"first_name"`
	LastName          string             `json:"last_name"`
	CurrencyCode      string             `json:"currency_code"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DisplayCurrencies string             `json:"display_currencies"`
	Language          string             `json:"language"`
}
