// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql/driver"
	"fmt"

	"github.com/horexdev/money-tracker/internal/domain"
	"github.com/jackc/pgx/v5/pgtype"
)

type AccountType string

const (
	AccountTypeChecking AccountType = "checking"
	AccountTypeSavings  AccountType = "savings"
	AccountTypeCash     AccountType = "cash"
	AccountTypeCredit   AccountType = "credit"
	AccountTypeCrypto   AccountType = "crypto"
)

func (e *AccountType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountType(s)
	case string:
		*e = AccountType(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountType: %T", src)
	}
	return nil
}

type NullAccountType struct {
	AccountType AccountType `json:"account_type"`
	Valid       bool        `json:"valid"` // Valid is true if AccountType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountType) Scan(value interface{}) error {
	if value == nil {
		ns.AccountType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountType), nil
}

type TransactionType string

const (
	TransactionTypeExpense TransactionType = "expense"
	TransactionTypeIncome  TransactionType = "income"
)

func (e *TransactionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionType(s)
	case string:
		*e = TransactionType(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionType: %T", src)
	}
	return nil
}

type NullTransactionType struct {
	TransactionType TransactionType `json:"transaction_type"`
	Valid           bool            `json:"valid"` // Valid is true if TransactionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionType) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionType), nil
}

type Account struct {
	ID             int64              `json:"id"`
	UserID         int64              `json:"user_id"`
	Name           string             `json:"name"`
	Icon           string             `json:"icon"`
	Color          string             `json:"color"`
	Type           AccountType        `json:"type"`
	CurrencyCode   string             `json:"currency_code"`
	IsDefault      bool               `json:"is_default"`
	IncludeInTotal bool               `json:"include_in_total"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Budget struct {
	ID                   int64              `json:"id"`
	UserID               int64              `json:"user_id"`
	CategoryID           int64              `json:"category_id"`
	LimitCents           int64              `json:"limit_cents"`
	Period               string             `json:"period"`
	CurrencyCode         string             `json:"currency_code"`
	NotifyAtPercent      int32              `json:"notify_at_percent"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	LastNotifiedAt       pgtype.Timestamptz `json:"last_notified_at"`
	NotificationsEnabled bool               `json:"notifications_enabled"`
	LastNotifiedPercent  int32              `json:"last_notified_percent"`
}

type Category struct {
	ID          int64              `json:"id"`
	UserID      pgtype.Int8        `json:"user_id"`
	Name        string             `json:"name"`
	Icon        string             `json:"icon"`
	Type        string             `json:"type"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	Color       string             `json:"color"`
	IsProtected bool               `json:"is_protected"`
}

type ExchangeRateSnapshot struct {
	ID             int64              `json:"id"`
	SnapshotDate   pgtype.Date        `json:"snapshot_date"`
	BaseCurrency   string             `json:"base_currency"`
	TargetCurrency string             `json:"target_currency"`
	Rate           pgtype.Numeric     `json:"rate"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type GoalTransaction struct {
	ID          int64              `json:"id"`
	GoalID      int64              `json:"goal_id"`
	UserID      int64              `json:"user_id"`
	Type        string             `json:"type"`
	AmountCents int64              `json:"amount_cents"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type RecurringTransaction struct {
	ID           int64                  `json:"id"`
	UserID       int64                  `json:"user_id"`
	CategoryID   int64                  `json:"category_id"`
	Type         domain.TransactionType `json:"type"`
	AmountCents  int64                  `json:"amount_cents"`
	CurrencyCode string                 `json:"currency_code"`
	Note         string                 `json:"note"`
	Frequency    string                 `json:"frequency"`
	NextRunAt    pgtype.Timestamptz     `json:"next_run_at"`
	IsActive     bool                   `json:"is_active"`
	CreatedAt    pgtype.Timestamptz     `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz     `json:"updated_at"`
	AccountID    int64                  `json:"account_id"`
}

type SavingsGoal struct {
	ID           int64              `json:"id"`
	UserID       int64              `json:"user_id"`
	Name         string             `json:"name"`
	TargetCents  int64              `json:"target_cents"`
	CurrentCents int64              `json:"current_cents"`
	CurrencyCode string             `json:"currency_code"`
	Deadline     pgtype.Date        `json:"deadline"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	AccountID    pgtype.Int8        `json:"account_id"`
}

type Transaction struct {
	ID           int64                  `json:"id"`
	UserID       int64                  `json:"user_id"`
	Type         domain.TransactionType `json:"type"`
	AmountCents  int64                  `json:"amount_cents"`
	CategoryID   int64                  `json:"category_id"`
	Note         string                 `json:"note"`
	CreatedAt    pgtype.Timestamptz     `json:"created_at"`
	CurrencyCode string                 `json:"currency_code"`
	AccountID    int64                  `json:"account_id"`
	IsAdjustment bool                   `json:"is_adjustment"`
	SnapshotDate pgtype.Date            `json:"snapshot_date"`
}

type Transfer struct {
	ID               int64              `json:"id"`
	UserID           int64              `json:"user_id"`
	FromAccountID    int64              `json:"from_account_id"`
	ToAccountID      int64              `json:"to_account_id"`
	AmountCents      int64              `json:"amount_cents"`
	FromCurrencyCode string             `json:"from_currency_code"`
	ToCurrencyCode   string             `json:"to_currency_code"`
	ExchangeRate     pgtype.Numeric     `json:"exchange_rate"`
	Note             string             `json:"note"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	FromTxID         pgtype.Int8        `json:"from_tx_id"`
	ToTxID           pgtype.Int8        `json:"to_tx_id"`
}

type User struct {
	ID                       int64              `json:"id"`
	Username                 string             `json:"username"`
	FirstName                string             `json:"first_name"`
	LastName                 string             `json:"last_name"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	DisplayCurrencies        string             `json:"display_currencies"`
	Language                 string             `json:"language"`
	NotifyBudgetAlerts       bool               `json:"notify_budget_alerts"`
	NotifyRecurringReminders bool               `json:"notify_recurring_reminders"`
	NotifyWeeklySummary      bool               `json:"notify_weekly_summary"`
	NotifyGoalMilestones     bool               `json:"notify_goal_milestones"`
	Theme                    string             `json:"theme"`
	HideAmounts              bool               `json:"hide_amounts"`
}
