// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountTransactionsByCategory(ctx context.Context, categoryID int64) (int64, error)
	CountUserTransactions(ctx context.Context, userID int64) (int64, error)
	CreateBudget(ctx context.Context, arg CreateBudgetParams) (Budget, error)
	CreateRecurring(ctx context.Context, arg CreateRecurringParams) (RecurringTransaction, error)
	CreateSavingsGoal(ctx context.Context, arg CreateSavingsGoalParams) (SavingsGoal, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUserCategory(ctx context.Context, arg CreateUserCategoryParams) (Category, error)
	DeleteBudget(ctx context.Context, arg DeleteBudgetParams) error
	DeleteRecurring(ctx context.Context, arg DeleteRecurringParams) error
	DeleteSavingsGoal(ctx context.Context, arg DeleteSavingsGoalParams) error
	DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) error
	DepositToGoal(ctx context.Context, arg DepositToGoalParams) (SavingsGoal, error)
	GetBalance(ctx context.Context, userID int64) (GetBalanceRow, error)
	GetBalanceByCurrency(ctx context.Context, userID int64) ([]GetBalanceByCurrencyRow, error)
	GetBudgetByID(ctx context.Context, arg GetBudgetByIDParams) (Budget, error)
	GetBudgetByUserCategoryPeriod(ctx context.Context, arg GetBudgetByUserCategoryPeriodParams) (Budget, error)
	GetCategoryByID(ctx context.Context, id int64) (Category, error)
	GetCategoryByName(ctx context.Context, arg GetCategoryByNameParams) (Category, error)
	GetDueRecurring(ctx context.Context, nextRunAt pgtype.Timestamptz) ([]RecurringTransaction, error)
	GetRecurringByID(ctx context.Context, arg GetRecurringByIDParams) (RecurringTransaction, error)
	GetSavingsGoalByID(ctx context.Context, arg GetSavingsGoalByIDParams) (SavingsGoal, error)
	GetSpentInPeriod(ctx context.Context, arg GetSpentInPeriodParams) (int64, error)
	GetStatsByCategory(ctx context.Context, arg GetStatsByCategoryParams) ([]GetStatsByCategoryRow, error)
	GetTotalInBaseCurrency(ctx context.Context, userID int64) (int64, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	ListBudgetsByUser(ctx context.Context, userID int64) ([]ListBudgetsByUserRow, error)
	ListRecurringByUser(ctx context.Context, userID int64) ([]ListRecurringByUserRow, error)
	ListSavingsGoalsByUser(ctx context.Context, userID int64) ([]SavingsGoal, error)
	ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]ListTransactionsRow, error)
	ListUserCategories(ctx context.Context, userID pgtype.Int8) ([]Category, error)
	ListUserCategoriesByType(ctx context.Context, arg ListUserCategoriesByTypeParams) ([]Category, error)
	SoftDeleteCategory(ctx context.Context, arg SoftDeleteCategoryParams) error
	ToggleRecurringActive(ctx context.Context, arg ToggleRecurringActiveParams) (RecurringTransaction, error)
	UpdateBudget(ctx context.Context, arg UpdateBudgetParams) (Budget, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateDisplayCurrencies(ctx context.Context, arg UpdateDisplayCurrenciesParams) (User, error)
	UpdateRecurring(ctx context.Context, arg UpdateRecurringParams) (RecurringTransaction, error)
	UpdateRecurringNextRun(ctx context.Context, arg UpdateRecurringNextRunParams) error
	UpdateSavingsGoal(ctx context.Context, arg UpdateSavingsGoalParams) (SavingsGoal, error)
	UpdateUserCurrency(ctx context.Context, arg UpdateUserCurrencyParams) (User, error)
	UpdateUserLanguage(ctx context.Context, arg UpdateUserLanguageParams) (User, error)
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
	WithdrawFromGoal(ctx context.Context, arg WithdrawFromGoalParams) (SavingsGoal, error)
}

var _ Querier = (*Queries)(nil)
