// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ClearDefaultAccounts(ctx context.Context, userID int64) error
	CountAccountRecurring(ctx context.Context, arg CountAccountRecurringParams) (int64, error)
	CountAccountTransactions(ctx context.Context, arg CountAccountTransactionsParams) (int64, error)
	CountAccountTransfers(ctx context.Context, arg CountAccountTransfersParams) (int64, error)
	CountActiveUsersInPeriod(ctx context.Context, arg CountActiveUsersInPeriodParams) (int64, error)
	CountAllUsers(ctx context.Context) (int64, error)
	CountNewUsers(ctx context.Context, arg CountNewUsersParams) (int64, error)
	CountRetainedUsers(ctx context.Context, arg CountRetainedUsersParams) (int64, error)
	CountTransactionsByCategory(ctx context.Context, categoryID int64) (int64, error)
	CountTransfersByUser(ctx context.Context, userID int64) (int64, error)
	CountUserAccounts(ctx context.Context, userID int64) (int64, error)
	CountUserTransactions(ctx context.Context, userID int64) (int64, error)
	CountUserTransactionsByAccount(ctx context.Context, arg CountUserTransactionsByAccountParams) (int64, error)
	CountUserTransactionsByAccountWithDateRange(ctx context.Context, arg CountUserTransactionsByAccountWithDateRangeParams) (int64, error)
	CountUserTransactionsWithDateRange(ctx context.Context, arg CountUserTransactionsWithDateRangeParams) (int64, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	// Creates a balance-adjustment transaction that is hidden from history and statistics
	// but is included in balance calculations. is_adjustment is always set to true.
	CreateAdjustmentTransaction(ctx context.Context, arg CreateAdjustmentTransactionParams) (Transaction, error)
	CreateBudget(ctx context.Context, arg CreateBudgetParams) (Budget, error)
	CreateRecurring(ctx context.Context, arg CreateRecurringParams) (RecurringTransaction, error)
	CreateSavingsGoal(ctx context.Context, arg CreateSavingsGoalParams) (SavingsGoal, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateTransactionWithDate(ctx context.Context, arg CreateTransactionWithDateParams) (Transaction, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	CreateUserCategory(ctx context.Context, arg CreateUserCategoryParams) (Category, error)
	DeleteAccount(ctx context.Context, arg DeleteAccountParams) error
	DeleteAllUserAccounts(ctx context.Context, userID int64) error
	DeleteAllUserBudgets(ctx context.Context, userID int64) error
	DeleteAllUserCategories(ctx context.Context, userID pgtype.Int8) error
	DeleteAllUserGoals(ctx context.Context, userID int64) error
	DeleteAllUserRecurring(ctx context.Context, userID int64) error
	DeleteAllUserTransactions(ctx context.Context, userID int64) error
	DeleteAllUserTransfers(ctx context.Context, userID int64) error
	DeleteBudget(ctx context.Context, arg DeleteBudgetParams) error
	DeleteRecurring(ctx context.Context, arg DeleteRecurringParams) error
	DeleteSavingsGoal(ctx context.Context, arg DeleteSavingsGoalParams) error
	DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) error
	DeleteTransfer(ctx context.Context, arg DeleteTransferParams) error
	DeleteUser(ctx context.Context, id int64) error
	DepositToGoal(ctx context.Context, arg DepositToGoalParams) (SavingsGoal, error)
	GetAccountBalance(ctx context.Context, arg GetAccountBalanceParams) (int64, error)
	GetAccountByID(ctx context.Context, arg GetAccountByIDParams) (Account, error)
	GetBalance(ctx context.Context, userID int64) (GetBalanceRow, error)
	GetBalanceByCurrency(ctx context.Context, userID int64) ([]GetBalanceByCurrencyRow, error)
	GetBalanceByCurrencyAndAccount(ctx context.Context, arg GetBalanceByCurrencyAndAccountParams) ([]GetBalanceByCurrencyAndAccountRow, error)
	GetBudgetByID(ctx context.Context, arg GetBudgetByIDParams) (Budget, error)
	GetBudgetByUserCategoryPeriod(ctx context.Context, arg GetBudgetByUserCategoryPeriodParams) (Budget, error)
	GetCategoryByID(ctx context.Context, id int64) (Category, error)
	GetCategoryByName(ctx context.Context, arg GetCategoryByNameParams) (Category, error)
	GetCategoryByTypeForUser(ctx context.Context, arg GetCategoryByTypeForUserParams) (Category, error)
	GetDefaultAccount(ctx context.Context, userID int64) (Account, error)
	GetDueRecurring(ctx context.Context, nextRunAt pgtype.Timestamptz) ([]RecurringTransaction, error)
	GetExchangeRate(ctx context.Context, arg GetExchangeRateParams) (pgtype.Numeric, error)
	// Returns the rate for the exact date, or the most recent rate before that date.
	GetExchangeRateOrLatest(ctx context.Context, arg GetExchangeRateOrLatestParams) (pgtype.Numeric, error)
	GetLatestSnapshotDate(ctx context.Context) (pgtype.Date, error)
	GetRecurringByID(ctx context.Context, arg GetRecurringByIDParams) (RecurringTransaction, error)
	GetSavingsGoalByID(ctx context.Context, arg GetSavingsGoalByIDParams) (SavingsGoal, error)
	// Cross-currency aggregation: converts each transaction's amount to the
	// budget's target currency using exchange_rate_snapshots. Same-currency
	// transactions pass through at rate 1.0 (no snapshot row needed).
	GetSpentInPeriod(ctx context.Context, arg GetSpentInPeriodParams) (int64, error)
	GetStatsByCategory(ctx context.Context, arg GetStatsByCategoryParams) ([]GetStatsByCategoryRow, error)
	GetStatsByCategoryAndAccount(ctx context.Context, arg GetStatsByCategoryAndAccountParams) ([]GetStatsByCategoryAndAccountRow, error)
	// Returns the system (user_id IS NULL) category of the given type.
	// Used for infrastructure categories like 'transfer' and 'adjustment'.
	GetSystemCategoryByType(ctx context.Context, type_ string) (Category, error)
	// Returns net balance (income - expense) summed across all transactions, converted to the
	// target currency using exchange_rate_snapshots. Same-currency transactions use rate 1.0.
	GetTotalInBaseCurrency(ctx context.Context, arg GetTotalInBaseCurrencyParams) (int64, error)
	GetTransferByID(ctx context.Context, arg GetTransferByIDParams) (GetTransferByIDRow, error)
	GetTransferTxIDs(ctx context.Context, arg GetTransferTxIDsParams) (GetTransferTxIDsRow, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	HasUserCategories(ctx context.Context, userID pgtype.Int8) (bool, error)
	InsertGoalTransaction(ctx context.Context, arg InsertGoalTransactionParams) error
	ListAccountsByUser(ctx context.Context, userID int64) ([]Account, error)
	ListAllUserIDs(ctx context.Context) ([]int64, error)
	ListAllUsers(ctx context.Context, arg ListAllUsersParams) ([]User, error)
	ListBudgetsByUser(ctx context.Context, userID int64) ([]ListBudgetsByUserRow, error)
	// Returns all distinct base currencies used across accounts (for daily cron).
	ListDistinctBaseCurrencies(ctx context.Context) ([]string, error)
	ListDistinctUsersWithBudgets(ctx context.Context) ([]int64, error)
	ListGoalTransactions(ctx context.Context, arg ListGoalTransactionsParams) ([]GoalTransaction, error)
	ListRecurringByUser(ctx context.Context, userID int64) ([]ListRecurringByUserRow, error)
	ListSavingsGoalsByUser(ctx context.Context, userID int64) ([]SavingsGoal, error)
	ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]ListTransactionsRow, error)
	ListTransactionsByAccount(ctx context.Context, arg ListTransactionsByAccountParams) ([]ListTransactionsByAccountRow, error)
	ListTransactionsByAccountWithDateRange(ctx context.Context, arg ListTransactionsByAccountWithDateRangeParams) ([]ListTransactionsByAccountWithDateRangeRow, error)
	ListTransactionsByCategoryPeriod(ctx context.Context, arg ListTransactionsByCategoryPeriodParams) ([]ListTransactionsByCategoryPeriodRow, error)
	ListTransactionsWithDateRange(ctx context.Context, arg ListTransactionsWithDateRangeParams) ([]ListTransactionsWithDateRangeRow, error)
	ListTransfersByAccount(ctx context.Context, arg ListTransfersByAccountParams) ([]ListTransfersByAccountRow, error)
	ListTransfersByUser(ctx context.Context, arg ListTransfersByUserParams) ([]ListTransfersByUserRow, error)
	ListUserCategories(ctx context.Context, userID pgtype.Int8) ([]Category, error)
	// Sorts a user's categories by transaction count (descending), name as tiebreaker.
	// The subquery aggregates without filtering by category type, so transactions
	// referencing transfer/adjustment system categories simply do not match the
	// outer JOIN and are discarded.
	ListUserCategoriesByFrequency(ctx context.Context, userID int64) ([]Category, error)
	// Same as ListUserCategoriesByFrequency, restricted to a single type plus 'both'.
	ListUserCategoriesByFrequencyAndType(ctx context.Context, arg ListUserCategoriesByFrequencyAndTypeParams) ([]Category, error)
	ListUserCategoriesByNameAsc(ctx context.Context, userID pgtype.Int8) ([]Category, error)
	ListUserCategoriesByNameDesc(ctx context.Context, userID pgtype.Int8) ([]Category, error)
	ListUserCategoriesByType(ctx context.Context, arg ListUserCategoriesByTypeParams) ([]Category, error)
	ListUserCategoriesByTypeFilterAsc(ctx context.Context, arg ListUserCategoriesByTypeFilterAscParams) ([]Category, error)
	ListUserCategoriesByTypeFilterDesc(ctx context.Context, arg ListUserCategoriesByTypeFilterDescParams) ([]Category, error)
	SetAccountDefault(ctx context.Context, arg SetAccountDefaultParams) (Account, error)
	SoftDeleteCategory(ctx context.Context, arg SoftDeleteCategoryParams) error
	ToggleRecurringActive(ctx context.Context, arg ToggleRecurringActiveParams) (RecurringTransaction, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateBudget(ctx context.Context, arg UpdateBudgetParams) (Budget, error)
	UpdateBudgetLastNotified(ctx context.Context, arg UpdateBudgetLastNotifiedParams) error
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateDisplayCurrencies(ctx context.Context, arg UpdateDisplayCurrenciesParams) (User, error)
	UpdateNotificationPreferences(ctx context.Context, arg UpdateNotificationPreferencesParams) (User, error)
	UpdateRecurring(ctx context.Context, arg UpdateRecurringParams) (RecurringTransaction, error)
	UpdateRecurringNextRun(ctx context.Context, arg UpdateRecurringNextRunParams) error
	UpdateSavingsGoal(ctx context.Context, arg UpdateSavingsGoalParams) (SavingsGoal, error)
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error)
	UpdateUserHideAmounts(ctx context.Context, arg UpdateUserHideAmountsParams) (User, error)
	UpdateUserLanguage(ctx context.Context, arg UpdateUserLanguageParams) (User, error)
	UpdateUserTheme(ctx context.Context, arg UpdateUserThemeParams) (User, error)
	UpsertExchangeRate(ctx context.Context, arg UpsertExchangeRateParams) error
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
	WithdrawFromGoal(ctx context.Context, arg WithdrawFromGoalParams) (SavingsGoal, error)
}

var _ Querier = (*Queries)(nil)
