// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recurring_transactions.sql

package sqlcgen

import (
	"context"

	"github.com/horexdev/money-tracker/internal/domain"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRecurring = `-- name: CreateRecurring :one
INSERT INTO recurring_transactions (user_id, account_id, category_id, type, amount_cents, currency_code, note, frequency, next_run_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, category_id, type, amount_cents, currency_code, note, frequency, next_run_at, is_active, created_at, updated_at, account_id
`

type CreateRecurringParams struct {
	UserID       int64                  `json:"user_id"`
	AccountID    int64                  `json:"account_id"`
	CategoryID   int64                  `json:"category_id"`
	Type         domain.TransactionType `json:"type"`
	AmountCents  int64                  `json:"amount_cents"`
	CurrencyCode string                 `json:"currency_code"`
	Note         string                 `json:"note"`
	Frequency    string                 `json:"frequency"`
	NextRunAt    pgtype.Timestamptz     `json:"next_run_at"`
}

func (q *Queries) CreateRecurring(ctx context.Context, arg CreateRecurringParams) (RecurringTransaction, error) {
	row := q.db.QueryRow(ctx, createRecurring,
		arg.UserID,
		arg.AccountID,
		arg.CategoryID,
		arg.Type,
		arg.AmountCents,
		arg.CurrencyCode,
		arg.Note,
		arg.Frequency,
		arg.NextRunAt,
	)
	var i RecurringTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Type,
		&i.AmountCents,
		&i.CurrencyCode,
		&i.Note,
		&i.Frequency,
		&i.NextRunAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountID,
	)
	return i, err
}

const deleteRecurring = `-- name: DeleteRecurring :exec
DELETE FROM recurring_transactions WHERE id = $1 AND user_id = $2
`

type DeleteRecurringParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteRecurring(ctx context.Context, arg DeleteRecurringParams) error {
	_, err := q.db.Exec(ctx, deleteRecurring, arg.ID, arg.UserID)
	return err
}

const getDueRecurring = `-- name: GetDueRecurring :many
SELECT id, user_id, category_id, type, amount_cents, currency_code, note, frequency, next_run_at, is_active, created_at, updated_at, account_id FROM recurring_transactions
WHERE is_active = true AND next_run_at <= $1
ORDER BY next_run_at ASC
LIMIT 100
`

func (q *Queries) GetDueRecurring(ctx context.Context, nextRunAt pgtype.Timestamptz) ([]RecurringTransaction, error) {
	rows, err := q.db.Query(ctx, getDueRecurring, nextRunAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecurringTransaction{}
	for rows.Next() {
		var i RecurringTransaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Type,
			&i.AmountCents,
			&i.CurrencyCode,
			&i.Note,
			&i.Frequency,
			&i.NextRunAt,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecurringByID = `-- name: GetRecurringByID :one
SELECT id, user_id, category_id, type, amount_cents, currency_code, note, frequency, next_run_at, is_active, created_at, updated_at, account_id FROM recurring_transactions WHERE id = $1 AND user_id = $2
`

type GetRecurringByIDParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetRecurringByID(ctx context.Context, arg GetRecurringByIDParams) (RecurringTransaction, error) {
	row := q.db.QueryRow(ctx, getRecurringByID, arg.ID, arg.UserID)
	var i RecurringTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Type,
		&i.AmountCents,
		&i.CurrencyCode,
		&i.Note,
		&i.Frequency,
		&i.NextRunAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountID,
	)
	return i, err
}

const listRecurringByUser = `-- name: ListRecurringByUser :many
SELECT
    r.id, r.user_id, r.category_id, r.type, r.amount_cents, r.currency_code, r.note, r.frequency, r.next_run_at, r.is_active, r.created_at, r.updated_at, r.account_id,
    c.name  AS category_name,
    c.icon AS category_icon,
    c.color AS category_color
FROM recurring_transactions r
JOIN categories c ON c.id = r.category_id
WHERE r.user_id = $1
ORDER BY r.created_at DESC
`

type ListRecurringByUserRow struct {
	ID            int64                  `json:"id"`
	UserID        int64                  `json:"user_id"`
	CategoryID    int64                  `json:"category_id"`
	Type          domain.TransactionType `json:"type"`
	AmountCents   int64                  `json:"amount_cents"`
	CurrencyCode  string                 `json:"currency_code"`
	Note          string                 `json:"note"`
	Frequency     string                 `json:"frequency"`
	NextRunAt     pgtype.Timestamptz     `json:"next_run_at"`
	IsActive      bool                   `json:"is_active"`
	CreatedAt     pgtype.Timestamptz     `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz     `json:"updated_at"`
	AccountID     int64                  `json:"account_id"`
	CategoryName  string                 `json:"category_name"`
	CategoryIcon  string                 `json:"category_icon"`
	CategoryColor string                 `json:"category_color"`
}

func (q *Queries) ListRecurringByUser(ctx context.Context, userID int64) ([]ListRecurringByUserRow, error) {
	rows, err := q.db.Query(ctx, listRecurringByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecurringByUserRow{}
	for rows.Next() {
		var i ListRecurringByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Type,
			&i.AmountCents,
			&i.CurrencyCode,
			&i.Note,
			&i.Frequency,
			&i.NextRunAt,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AccountID,
			&i.CategoryName,
			&i.CategoryIcon,
			&i.CategoryColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleRecurringActive = `-- name: ToggleRecurringActive :one
UPDATE recurring_transactions
SET is_active  = NOT is_active,
    updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, category_id, type, amount_cents, currency_code, note, frequency, next_run_at, is_active, created_at, updated_at, account_id
`

type ToggleRecurringActiveParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) ToggleRecurringActive(ctx context.Context, arg ToggleRecurringActiveParams) (RecurringTransaction, error) {
	row := q.db.QueryRow(ctx, toggleRecurringActive, arg.ID, arg.UserID)
	var i RecurringTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Type,
		&i.AmountCents,
		&i.CurrencyCode,
		&i.Note,
		&i.Frequency,
		&i.NextRunAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountID,
	)
	return i, err
}

const updateRecurring = `-- name: UpdateRecurring :one
UPDATE recurring_transactions
SET account_id    = $3,
    category_id   = $4,
    type          = $5,
    amount_cents  = $6,
    currency_code = $7,
    note          = $8,
    frequency     = $9,
    next_run_at   = $10,
    updated_at    = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, category_id, type, amount_cents, currency_code, note, frequency, next_run_at, is_active, created_at, updated_at, account_id
`

type UpdateRecurringParams struct {
	ID           int64                  `json:"id"`
	UserID       int64                  `json:"user_id"`
	AccountID    int64                  `json:"account_id"`
	CategoryID   int64                  `json:"category_id"`
	Type         domain.TransactionType `json:"type"`
	AmountCents  int64                  `json:"amount_cents"`
	CurrencyCode string                 `json:"currency_code"`
	Note         string                 `json:"note"`
	Frequency    string                 `json:"frequency"`
	NextRunAt    pgtype.Timestamptz     `json:"next_run_at"`
}

func (q *Queries) UpdateRecurring(ctx context.Context, arg UpdateRecurringParams) (RecurringTransaction, error) {
	row := q.db.QueryRow(ctx, updateRecurring,
		arg.ID,
		arg.UserID,
		arg.AccountID,
		arg.CategoryID,
		arg.Type,
		arg.AmountCents,
		arg.CurrencyCode,
		arg.Note,
		arg.Frequency,
		arg.NextRunAt,
	)
	var i RecurringTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Type,
		&i.AmountCents,
		&i.CurrencyCode,
		&i.Note,
		&i.Frequency,
		&i.NextRunAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountID,
	)
	return i, err
}

const updateRecurringNextRun = `-- name: UpdateRecurringNextRun :exec
UPDATE recurring_transactions
SET next_run_at = $2,
    updated_at  = now()
WHERE id = $1
`

type UpdateRecurringNextRunParams struct {
	ID        int64              `json:"id"`
	NextRunAt pgtype.Timestamptz `json:"next_run_at"`
}

func (q *Queries) UpdateRecurringNextRun(ctx context.Context, arg UpdateRecurringNextRunParams) error {
	_, err := q.db.Exec(ctx, updateRecurringNextRun, arg.ID, arg.NextRunAt)
	return err
}
