// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: savings_goals.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSavingsGoal = `-- name: CreateSavingsGoal :one
INSERT INTO savings_goals (user_id, name, target_cents, currency_code, deadline)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, target_cents, current_cents, currency_code, deadline, created_at, updated_at, account_id
`

type CreateSavingsGoalParams struct {
	UserID       int64       `json:"user_id"`
	Name         string      `json:"name"`
	TargetCents  int64       `json:"target_cents"`
	CurrencyCode string      `json:"currency_code"`
	Deadline     pgtype.Date `json:"deadline"`
}

func (q *Queries) CreateSavingsGoal(ctx context.Context, arg CreateSavingsGoalParams) (SavingsGoal, error) {
	row := q.db.QueryRow(ctx, createSavingsGoal,
		arg.UserID,
		arg.Name,
		arg.TargetCents,
		arg.CurrencyCode,
		arg.Deadline,
	)
	var i SavingsGoal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TargetCents,
		&i.CurrentCents,
		&i.CurrencyCode,
		&i.Deadline,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountID,
	)
	return i, err
}

const deleteSavingsGoal = `-- name: DeleteSavingsGoal :exec
DELETE FROM savings_goals WHERE id = $1 AND user_id = $2
`

type DeleteSavingsGoalParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteSavingsGoal(ctx context.Context, arg DeleteSavingsGoalParams) error {
	_, err := q.db.Exec(ctx, deleteSavingsGoal, arg.ID, arg.UserID)
	return err
}

const depositToGoal = `-- name: DepositToGoal :one
UPDATE savings_goals
SET current_cents = current_cents + $3,
    updated_at    = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, target_cents, current_cents, currency_code, deadline, created_at, updated_at, account_id
`

type DepositToGoalParams struct {
	ID           int64 `json:"id"`
	UserID       int64 `json:"user_id"`
	CurrentCents int64 `json:"current_cents"`
}

func (q *Queries) DepositToGoal(ctx context.Context, arg DepositToGoalParams) (SavingsGoal, error) {
	row := q.db.QueryRow(ctx, depositToGoal, arg.ID, arg.UserID, arg.CurrentCents)
	var i SavingsGoal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TargetCents,
		&i.CurrentCents,
		&i.CurrencyCode,
		&i.Deadline,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountID,
	)
	return i, err
}

const getSavingsGoalByID = `-- name: GetSavingsGoalByID :one
SELECT id, user_id, name, target_cents, current_cents, currency_code, deadline, created_at, updated_at, account_id FROM savings_goals WHERE id = $1 AND user_id = $2
`

type GetSavingsGoalByIDParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetSavingsGoalByID(ctx context.Context, arg GetSavingsGoalByIDParams) (SavingsGoal, error) {
	row := q.db.QueryRow(ctx, getSavingsGoalByID, arg.ID, arg.UserID)
	var i SavingsGoal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TargetCents,
		&i.CurrentCents,
		&i.CurrencyCode,
		&i.Deadline,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountID,
	)
	return i, err
}

const listSavingsGoalsByUser = `-- name: ListSavingsGoalsByUser :many
SELECT id, user_id, name, target_cents, current_cents, currency_code, deadline, created_at, updated_at, account_id FROM savings_goals
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSavingsGoalsByUser(ctx context.Context, userID int64) ([]SavingsGoal, error) {
	rows, err := q.db.Query(ctx, listSavingsGoalsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SavingsGoal{}
	for rows.Next() {
		var i SavingsGoal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TargetCents,
			&i.CurrentCents,
			&i.CurrencyCode,
			&i.Deadline,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSavingsGoal = `-- name: UpdateSavingsGoal :one
UPDATE savings_goals
SET name          = $3,
    target_cents  = $4,
    currency_code = $5,
    deadline      = $6,
    updated_at    = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, target_cents, current_cents, currency_code, deadline, created_at, updated_at, account_id
`

type UpdateSavingsGoalParams struct {
	ID           int64       `json:"id"`
	UserID       int64       `json:"user_id"`
	Name         string      `json:"name"`
	TargetCents  int64       `json:"target_cents"`
	CurrencyCode string      `json:"currency_code"`
	Deadline     pgtype.Date `json:"deadline"`
}

func (q *Queries) UpdateSavingsGoal(ctx context.Context, arg UpdateSavingsGoalParams) (SavingsGoal, error) {
	row := q.db.QueryRow(ctx, updateSavingsGoal,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.TargetCents,
		arg.CurrencyCode,
		arg.Deadline,
	)
	var i SavingsGoal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TargetCents,
		&i.CurrentCents,
		&i.CurrencyCode,
		&i.Deadline,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountID,
	)
	return i, err
}

const withdrawFromGoal = `-- name: WithdrawFromGoal :one
UPDATE savings_goals
SET current_cents = current_cents - $3,
    updated_at    = now()
WHERE id = $1 AND user_id = $2 AND current_cents >= $3
RETURNING id, user_id, name, target_cents, current_cents, currency_code, deadline, created_at, updated_at, account_id
`

type WithdrawFromGoalParams struct {
	ID           int64 `json:"id"`
	UserID       int64 `json:"user_id"`
	CurrentCents int64 `json:"current_cents"`
}

func (q *Queries) WithdrawFromGoal(ctx context.Context, arg WithdrawFromGoalParams) (SavingsGoal, error) {
	row := q.db.QueryRow(ctx, withdrawFromGoal, arg.ID, arg.UserID, arg.CurrentCents)
	var i SavingsGoal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TargetCents,
		&i.CurrentCents,
		&i.CurrencyCode,
		&i.Deadline,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountID,
	)
	return i, err
}
