// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package sqlcgen

import (
	"context"

	"github.com/horexdev/money-tracker/internal/domain"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUserTransactions = `-- name: CountUserTransactions :one
SELECT count(*)::BIGINT FROM transactions WHERE user_id = $1 AND is_adjustment = false
`

func (q *Queries) CountUserTransactions(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countUserTransactions, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countUserTransactionsByAccount = `-- name: CountUserTransactionsByAccount :one
SELECT count(*)::BIGINT FROM transactions WHERE user_id = $1 AND account_id = $2 AND is_adjustment = false
`

type CountUserTransactionsByAccountParams struct {
	UserID    int64 `json:"user_id"`
	AccountID int64 `json:"account_id"`
}

func (q *Queries) CountUserTransactionsByAccount(ctx context.Context, arg CountUserTransactionsByAccountParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserTransactionsByAccount, arg.UserID, arg.AccountID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countUserTransactionsByAccountWithDateRange = `-- name: CountUserTransactionsByAccountWithDateRange :one
SELECT count(*)::BIGINT FROM transactions
WHERE user_id = $1 AND account_id = $2 AND is_adjustment = false
  AND ($3::TIMESTAMPTZ IS NULL OR created_at >= $3)
  AND ($4::TIMESTAMPTZ IS NULL OR created_at <= $4)
`

type CountUserTransactionsByAccountWithDateRangeParams struct {
	UserID    int64              `json:"user_id"`
	AccountID int64              `json:"account_id"`
	Column3   pgtype.Timestamptz `json:"column_3"`
	Column4   pgtype.Timestamptz `json:"column_4"`
}

func (q *Queries) CountUserTransactionsByAccountWithDateRange(ctx context.Context, arg CountUserTransactionsByAccountWithDateRangeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserTransactionsByAccountWithDateRange,
		arg.UserID,
		arg.AccountID,
		arg.Column3,
		arg.Column4,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countUserTransactionsWithDateRange = `-- name: CountUserTransactionsWithDateRange :one
SELECT count(*)::BIGINT FROM transactions
WHERE user_id = $1 AND is_adjustment = false
  AND ($2::TIMESTAMPTZ IS NULL OR created_at >= $2)
  AND ($3::TIMESTAMPTZ IS NULL OR created_at <= $3)
`

type CountUserTransactionsWithDateRangeParams struct {
	UserID  int64              `json:"user_id"`
	Column2 pgtype.Timestamptz `json:"column_2"`
	Column3 pgtype.Timestamptz `json:"column_3"`
}

func (q *Queries) CountUserTransactionsWithDateRange(ctx context.Context, arg CountUserTransactionsWithDateRangeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserTransactionsWithDateRange, arg.UserID, arg.Column2, arg.Column3)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createAdjustmentTransaction = `-- name: CreateAdjustmentTransaction :one
INSERT INTO transactions (user_id, type, amount_cents, category_id, note,
    currency_code, account_id, snapshot_date, is_adjustment)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, true)
RETURNING id, user_id, type, amount_cents, category_id, note, created_at, currency_code, account_id, is_adjustment, snapshot_date
`

type CreateAdjustmentTransactionParams struct {
	UserID       int64                  `json:"user_id"`
	Type         domain.TransactionType `json:"type"`
	AmountCents  int64                  `json:"amount_cents"`
	CategoryID   int64                  `json:"category_id"`
	Note         string                 `json:"note"`
	CurrencyCode string                 `json:"currency_code"`
	AccountID    int64                  `json:"account_id"`
	SnapshotDate pgtype.Date            `json:"snapshot_date"`
}

// Creates a balance-adjustment transaction that is hidden from history and statistics
// but is included in balance calculations. is_adjustment is always set to true.
func (q *Queries) CreateAdjustmentTransaction(ctx context.Context, arg CreateAdjustmentTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createAdjustmentTransaction,
		arg.UserID,
		arg.Type,
		arg.AmountCents,
		arg.CategoryID,
		arg.Note,
		arg.CurrencyCode,
		arg.AccountID,
		arg.SnapshotDate,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.AmountCents,
		&i.CategoryID,
		&i.Note,
		&i.CreatedAt,
		&i.CurrencyCode,
		&i.AccountID,
		&i.IsAdjustment,
		&i.SnapshotDate,
	)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (user_id, type, amount_cents, category_id, note, currency_code, account_id, snapshot_date)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, type, amount_cents, category_id, note, created_at, currency_code, account_id, is_adjustment, snapshot_date
`

type CreateTransactionParams struct {
	UserID       int64                  `json:"user_id"`
	Type         domain.TransactionType `json:"type"`
	AmountCents  int64                  `json:"amount_cents"`
	CategoryID   int64                  `json:"category_id"`
	Note         string                 `json:"note"`
	CurrencyCode string                 `json:"currency_code"`
	AccountID    int64                  `json:"account_id"`
	SnapshotDate pgtype.Date            `json:"snapshot_date"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.Type,
		arg.AmountCents,
		arg.CategoryID,
		arg.Note,
		arg.CurrencyCode,
		arg.AccountID,
		arg.SnapshotDate,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.AmountCents,
		&i.CategoryID,
		&i.Note,
		&i.CreatedAt,
		&i.CurrencyCode,
		&i.AccountID,
		&i.IsAdjustment,
		&i.SnapshotDate,
	)
	return i, err
}

const createTransactionWithDate = `-- name: CreateTransactionWithDate :one
INSERT INTO transactions (user_id, type, amount_cents, category_id, note, currency_code, created_at, account_id, snapshot_date)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, type, amount_cents, category_id, note, created_at, currency_code, account_id, is_adjustment, snapshot_date
`

type CreateTransactionWithDateParams struct {
	UserID       int64                  `json:"user_id"`
	Type         domain.TransactionType `json:"type"`
	AmountCents  int64                  `json:"amount_cents"`
	CategoryID   int64                  `json:"category_id"`
	Note         string                 `json:"note"`
	CurrencyCode string                 `json:"currency_code"`
	CreatedAt    pgtype.Timestamptz     `json:"created_at"`
	AccountID    int64                  `json:"account_id"`
	SnapshotDate pgtype.Date            `json:"snapshot_date"`
}

func (q *Queries) CreateTransactionWithDate(ctx context.Context, arg CreateTransactionWithDateParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransactionWithDate,
		arg.UserID,
		arg.Type,
		arg.AmountCents,
		arg.CategoryID,
		arg.Note,
		arg.CurrencyCode,
		arg.CreatedAt,
		arg.AccountID,
		arg.SnapshotDate,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.AmountCents,
		&i.CategoryID,
		&i.Note,
		&i.CreatedAt,
		&i.CurrencyCode,
		&i.AccountID,
		&i.IsAdjustment,
		&i.SnapshotDate,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions WHERE id = $1 AND user_id = $2
`

type DeleteTransactionParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) error {
	_, err := q.db.Exec(ctx, deleteTransaction, arg.ID, arg.UserID)
	return err
}

const getBalance = `-- name: GetBalance :one
SELECT
    COALESCE(SUM(CASE WHEN type = 'income'  THEN amount_cents ELSE 0 END), 0)::BIGINT AS total_income,
    COALESCE(SUM(CASE WHEN type = 'expense' THEN amount_cents ELSE 0 END), 0)::BIGINT AS total_expense
FROM transactions
WHERE user_id = $1 AND is_adjustment = false
`

type GetBalanceRow struct {
	TotalIncome  int64 `json:"total_income"`
	TotalExpense int64 `json:"total_expense"`
}

func (q *Queries) GetBalance(ctx context.Context, userID int64) (GetBalanceRow, error) {
	row := q.db.QueryRow(ctx, getBalance, userID)
	var i GetBalanceRow
	err := row.Scan(&i.TotalIncome, &i.TotalExpense)
	return i, err
}

const getBalanceByCurrency = `-- name: GetBalanceByCurrency :many
SELECT
    currency_code,
    COALESCE(SUM(CASE WHEN type = 'income'  THEN amount_cents ELSE 0 END), 0)::BIGINT AS total_income,
    COALESCE(SUM(CASE WHEN type = 'expense' THEN amount_cents ELSE 0 END), 0)::BIGINT AS total_expense
FROM transactions
WHERE user_id = $1 AND is_adjustment = false
GROUP BY currency_code
`

type GetBalanceByCurrencyRow struct {
	CurrencyCode string `json:"currency_code"`
	TotalIncome  int64  `json:"total_income"`
	TotalExpense int64  `json:"total_expense"`
}

func (q *Queries) GetBalanceByCurrency(ctx context.Context, userID int64) ([]GetBalanceByCurrencyRow, error) {
	rows, err := q.db.Query(ctx, getBalanceByCurrency, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBalanceByCurrencyRow{}
	for rows.Next() {
		var i GetBalanceByCurrencyRow
		if err := rows.Scan(&i.CurrencyCode, &i.TotalIncome, &i.TotalExpense); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBalanceByCurrencyAndAccount = `-- name: GetBalanceByCurrencyAndAccount :many
SELECT
    currency_code,
    COALESCE(SUM(CASE WHEN type = 'income'  THEN amount_cents ELSE 0 END), 0)::BIGINT AS total_income,
    COALESCE(SUM(CASE WHEN type = 'expense' THEN amount_cents ELSE 0 END), 0)::BIGINT AS total_expense
FROM transactions
WHERE user_id = $1 AND account_id = $2 AND is_adjustment = false
GROUP BY currency_code
`

type GetBalanceByCurrencyAndAccountParams struct {
	UserID    int64 `json:"user_id"`
	AccountID int64 `json:"account_id"`
}

type GetBalanceByCurrencyAndAccountRow struct {
	CurrencyCode string `json:"currency_code"`
	TotalIncome  int64  `json:"total_income"`
	TotalExpense int64  `json:"total_expense"`
}

func (q *Queries) GetBalanceByCurrencyAndAccount(ctx context.Context, arg GetBalanceByCurrencyAndAccountParams) ([]GetBalanceByCurrencyAndAccountRow, error) {
	rows, err := q.db.Query(ctx, getBalanceByCurrencyAndAccount, arg.UserID, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBalanceByCurrencyAndAccountRow{}
	for rows.Next() {
		var i GetBalanceByCurrencyAndAccountRow
		if err := rows.Scan(&i.CurrencyCode, &i.TotalIncome, &i.TotalExpense); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatsByCategory = `-- name: GetStatsByCategory :many
SELECT
    c.name              AS category_name,
    c.icon             AS category_icon,
    c.color             AS category_color,
    t.type,
    t.currency_code,
    SUM(t.amount_cents)::BIGINT AS total_cents,
    COUNT(*)::BIGINT    AS tx_count
FROM transactions t
JOIN categories c ON c.id = t.category_id
WHERE t.user_id   = $1
  AND t.created_at >= $2
  AND t.created_at <  $3
  AND t.is_adjustment = false
GROUP BY c.name, c.icon, c.color, t.type, t.currency_code
ORDER BY total_cents DESC
`

type GetStatsByCategoryParams struct {
	UserID      int64              `json:"user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

type GetStatsByCategoryRow struct {
	CategoryName  string                 `json:"category_name"`
	CategoryIcon  string                 `json:"category_icon"`
	CategoryColor string                 `json:"category_color"`
	Type          domain.TransactionType `json:"type"`
	CurrencyCode  string                 `json:"currency_code"`
	TotalCents    int64                  `json:"total_cents"`
	TxCount       int64                  `json:"tx_count"`
}

func (q *Queries) GetStatsByCategory(ctx context.Context, arg GetStatsByCategoryParams) ([]GetStatsByCategoryRow, error) {
	rows, err := q.db.Query(ctx, getStatsByCategory, arg.UserID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStatsByCategoryRow{}
	for rows.Next() {
		var i GetStatsByCategoryRow
		if err := rows.Scan(
			&i.CategoryName,
			&i.CategoryIcon,
			&i.CategoryColor,
			&i.Type,
			&i.CurrencyCode,
			&i.TotalCents,
			&i.TxCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatsByCategoryAndAccount = `-- name: GetStatsByCategoryAndAccount :many
SELECT
    c.name              AS category_name,
    c.icon             AS category_icon,
    c.color             AS category_color,
    t.type,
    t.currency_code,
    SUM(t.amount_cents)::BIGINT AS total_cents,
    COUNT(*)::BIGINT    AS tx_count
FROM transactions t
JOIN categories c ON c.id = t.category_id
WHERE t.user_id    = $1
  AND t.account_id = $2
  AND t.created_at >= $3
  AND t.created_at <  $4
  AND t.is_adjustment = false
GROUP BY c.name, c.icon, c.color, t.type, t.currency_code
ORDER BY total_cents DESC
`

type GetStatsByCategoryAndAccountParams struct {
	UserID      int64              `json:"user_id"`
	AccountID   int64              `json:"account_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

type GetStatsByCategoryAndAccountRow struct {
	CategoryName  string                 `json:"category_name"`
	CategoryIcon  string                 `json:"category_icon"`
	CategoryColor string                 `json:"category_color"`
	Type          domain.TransactionType `json:"type"`
	CurrencyCode  string                 `json:"currency_code"`
	TotalCents    int64                  `json:"total_cents"`
	TxCount       int64                  `json:"tx_count"`
}

func (q *Queries) GetStatsByCategoryAndAccount(ctx context.Context, arg GetStatsByCategoryAndAccountParams) ([]GetStatsByCategoryAndAccountRow, error) {
	rows, err := q.db.Query(ctx, getStatsByCategoryAndAccount,
		arg.UserID,
		arg.AccountID,
		arg.CreatedAt,
		arg.CreatedAt_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStatsByCategoryAndAccountRow{}
	for rows.Next() {
		var i GetStatsByCategoryAndAccountRow
		if err := rows.Scan(
			&i.CategoryName,
			&i.CategoryIcon,
			&i.CategoryColor,
			&i.Type,
			&i.CurrencyCode,
			&i.TotalCents,
			&i.TxCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalInBaseCurrency = `-- name: GetTotalInBaseCurrency :one
SELECT COALESCE(SUM(
    ROUND(
        CASE WHEN t.type = 'income' THEN t.amount_cents ELSE -t.amount_cents END
        * COALESCE(ers.rate, 1.0)
    )
), 0)::BIGINT AS total_net_base_cents
FROM transactions t
LEFT JOIN exchange_rate_snapshots ers
    ON ers.snapshot_date   = t.snapshot_date
   AND ers.base_currency   = t.currency_code
   AND ers.target_currency = $2
WHERE t.user_id = $1 AND t.is_adjustment = false
`

type GetTotalInBaseCurrencyParams struct {
	UserID         int64  `json:"user_id"`
	TargetCurrency string `json:"target_currency"`
}

// Returns net balance (income - expense) summed across all transactions, converted to the
// target currency using exchange_rate_snapshots. Same-currency transactions use rate 1.0.
func (q *Queries) GetTotalInBaseCurrency(ctx context.Context, arg GetTotalInBaseCurrencyParams) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalInBaseCurrency, arg.UserID, arg.TargetCurrency)
	var total_net_base_cents int64
	err := row.Scan(&total_net_base_cents)
	return total_net_base_cents, err
}

const listTransactions = `-- name: ListTransactions :many
SELECT
    t.id,
    t.user_id,
    t.type,
    t.amount_cents,
    t.category_id,
    t.note,
    t.created_at,
    t.currency_code,
    c.name  AS category_name,
    c.icon AS category_icon,
    c.color AS category_color
FROM transactions t
JOIN categories c ON c.id = t.category_id
WHERE t.user_id = $1
  AND t.is_adjustment = false
ORDER BY t.created_at DESC
LIMIT $2 OFFSET $3
`

type ListTransactionsParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListTransactionsRow struct {
	ID            int64                  `json:"id"`
	UserID        int64                  `json:"user_id"`
	Type          domain.TransactionType `json:"type"`
	AmountCents   int64                  `json:"amount_cents"`
	CategoryID    int64                  `json:"category_id"`
	Note          string                 `json:"note"`
	CreatedAt     pgtype.Timestamptz     `json:"created_at"`
	CurrencyCode  string                 `json:"currency_code"`
	CategoryName  string                 `json:"category_name"`
	CategoryIcon  string                 `json:"category_icon"`
	CategoryColor string                 `json:"category_color"`
}

func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]ListTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listTransactions, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsRow{}
	for rows.Next() {
		var i ListTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.AmountCents,
			&i.CategoryID,
			&i.Note,
			&i.CreatedAt,
			&i.CurrencyCode,
			&i.CategoryName,
			&i.CategoryIcon,
			&i.CategoryColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByAccount = `-- name: ListTransactionsByAccount :many
SELECT
    t.id,
    t.user_id,
    t.type,
    t.amount_cents,
    t.category_id,
    t.note,
    t.created_at,
    t.currency_code,
    c.name  AS category_name,
    c.icon AS category_icon,
    c.color AS category_color
FROM transactions t
JOIN categories c ON c.id = t.category_id
WHERE t.user_id = $1 AND t.account_id = $2
  AND t.is_adjustment = false
ORDER BY t.created_at DESC
LIMIT $3 OFFSET $4
`

type ListTransactionsByAccountParams struct {
	UserID    int64 `json:"user_id"`
	AccountID int64 `json:"account_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

type ListTransactionsByAccountRow struct {
	ID            int64                  `json:"id"`
	UserID        int64                  `json:"user_id"`
	Type          domain.TransactionType `json:"type"`
	AmountCents   int64                  `json:"amount_cents"`
	CategoryID    int64                  `json:"category_id"`
	Note          string                 `json:"note"`
	CreatedAt     pgtype.Timestamptz     `json:"created_at"`
	CurrencyCode  string                 `json:"currency_code"`
	CategoryName  string                 `json:"category_name"`
	CategoryIcon  string                 `json:"category_icon"`
	CategoryColor string                 `json:"category_color"`
}

func (q *Queries) ListTransactionsByAccount(ctx context.Context, arg ListTransactionsByAccountParams) ([]ListTransactionsByAccountRow, error) {
	rows, err := q.db.Query(ctx, listTransactionsByAccount,
		arg.UserID,
		arg.AccountID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsByAccountRow{}
	for rows.Next() {
		var i ListTransactionsByAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.AmountCents,
			&i.CategoryID,
			&i.Note,
			&i.CreatedAt,
			&i.CurrencyCode,
			&i.CategoryName,
			&i.CategoryIcon,
			&i.CategoryColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByAccountWithDateRange = `-- name: ListTransactionsByAccountWithDateRange :many
SELECT
    t.id,
    t.user_id,
    t.type,
    t.amount_cents,
    t.category_id,
    t.note,
    t.created_at,
    t.currency_code,
    t.account_id,
    c.name  AS category_name,
    c.icon AS category_icon,
    c.color AS category_color,
    a.name  AS account_name
FROM transactions t
JOIN categories c ON c.id = t.category_id
LEFT JOIN accounts a ON a.id = t.account_id
WHERE t.user_id = $1 AND t.account_id = $2
  AND t.is_adjustment = false
  AND ($5::TIMESTAMPTZ IS NULL OR t.created_at >= $5)
  AND ($6::TIMESTAMPTZ IS NULL OR t.created_at <= $6)
ORDER BY t.created_at DESC
LIMIT $3 OFFSET $4
`

type ListTransactionsByAccountWithDateRangeParams struct {
	UserID    int64              `json:"user_id"`
	AccountID int64              `json:"account_id"`
	Limit     int32              `json:"limit"`
	Offset    int32              `json:"offset"`
	Column5   pgtype.Timestamptz `json:"column_5"`
	Column6   pgtype.Timestamptz `json:"column_6"`
}

type ListTransactionsByAccountWithDateRangeRow struct {
	ID            int64                  `json:"id"`
	UserID        int64                  `json:"user_id"`
	Type          domain.TransactionType `json:"type"`
	AmountCents   int64                  `json:"amount_cents"`
	CategoryID    int64                  `json:"category_id"`
	Note          string                 `json:"note"`
	CreatedAt     pgtype.Timestamptz     `json:"created_at"`
	CurrencyCode  string                 `json:"currency_code"`
	AccountID     int64                  `json:"account_id"`
	CategoryName  string                 `json:"category_name"`
	CategoryIcon  string                 `json:"category_icon"`
	CategoryColor string                 `json:"category_color"`
	AccountName   pgtype.Text            `json:"account_name"`
}

func (q *Queries) ListTransactionsByAccountWithDateRange(ctx context.Context, arg ListTransactionsByAccountWithDateRangeParams) ([]ListTransactionsByAccountWithDateRangeRow, error) {
	rows, err := q.db.Query(ctx, listTransactionsByAccountWithDateRange,
		arg.UserID,
		arg.AccountID,
		arg.Limit,
		arg.Offset,
		arg.Column5,
		arg.Column6,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsByAccountWithDateRangeRow{}
	for rows.Next() {
		var i ListTransactionsByAccountWithDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.AmountCents,
			&i.CategoryID,
			&i.Note,
			&i.CreatedAt,
			&i.CurrencyCode,
			&i.AccountID,
			&i.CategoryName,
			&i.CategoryIcon,
			&i.CategoryColor,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByCategoryPeriod = `-- name: ListTransactionsByCategoryPeriod :many
SELECT
    t.id,
    t.user_id,
    t.type,
    t.amount_cents,
    t.category_id,
    t.note,
    t.created_at,
    t.currency_code,
    c.name  AS category_name,
    c.icon AS category_icon,
    c.color AS category_color
FROM transactions t
JOIN categories c ON c.id = t.category_id
WHERE t.user_id      = $1
  AND t.category_id  = $2
  AND t.type         = 'expense'
  AND t.created_at  >= $3
  AND t.created_at  <  $4
  AND t.is_adjustment = false
ORDER BY t.created_at DESC
`

type ListTransactionsByCategoryPeriodParams struct {
	UserID      int64              `json:"user_id"`
	CategoryID  int64              `json:"category_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

type ListTransactionsByCategoryPeriodRow struct {
	ID            int64                  `json:"id"`
	UserID        int64                  `json:"user_id"`
	Type          domain.TransactionType `json:"type"`
	AmountCents   int64                  `json:"amount_cents"`
	CategoryID    int64                  `json:"category_id"`
	Note          string                 `json:"note"`
	CreatedAt     pgtype.Timestamptz     `json:"created_at"`
	CurrencyCode  string                 `json:"currency_code"`
	CategoryName  string                 `json:"category_name"`
	CategoryIcon  string                 `json:"category_icon"`
	CategoryColor string                 `json:"category_color"`
}

func (q *Queries) ListTransactionsByCategoryPeriod(ctx context.Context, arg ListTransactionsByCategoryPeriodParams) ([]ListTransactionsByCategoryPeriodRow, error) {
	rows, err := q.db.Query(ctx, listTransactionsByCategoryPeriod,
		arg.UserID,
		arg.CategoryID,
		arg.CreatedAt,
		arg.CreatedAt_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsByCategoryPeriodRow{}
	for rows.Next() {
		var i ListTransactionsByCategoryPeriodRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.AmountCents,
			&i.CategoryID,
			&i.Note,
			&i.CreatedAt,
			&i.CurrencyCode,
			&i.CategoryName,
			&i.CategoryIcon,
			&i.CategoryColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsWithDateRange = `-- name: ListTransactionsWithDateRange :many
SELECT
    t.id,
    t.user_id,
    t.type,
    t.amount_cents,
    t.category_id,
    t.note,
    t.created_at,
    t.currency_code,
    t.account_id,
    c.name  AS category_name,
    c.icon AS category_icon,
    c.color AS category_color,
    a.name  AS account_name
FROM transactions t
JOIN categories c ON c.id = t.category_id
LEFT JOIN accounts a ON a.id = t.account_id
WHERE t.user_id = $1
  AND t.is_adjustment = false
  AND ($4::TIMESTAMPTZ IS NULL OR t.created_at >= $4)
  AND ($5::TIMESTAMPTZ IS NULL OR t.created_at <= $5)
ORDER BY t.created_at DESC
LIMIT $2 OFFSET $3
`

type ListTransactionsWithDateRangeParams struct {
	UserID  int64              `json:"user_id"`
	Limit   int32              `json:"limit"`
	Offset  int32              `json:"offset"`
	Column4 pgtype.Timestamptz `json:"column_4"`
	Column5 pgtype.Timestamptz `json:"column_5"`
}

type ListTransactionsWithDateRangeRow struct {
	ID            int64                  `json:"id"`
	UserID        int64                  `json:"user_id"`
	Type          domain.TransactionType `json:"type"`
	AmountCents   int64                  `json:"amount_cents"`
	CategoryID    int64                  `json:"category_id"`
	Note          string                 `json:"note"`
	CreatedAt     pgtype.Timestamptz     `json:"created_at"`
	CurrencyCode  string                 `json:"currency_code"`
	AccountID     int64                  `json:"account_id"`
	CategoryName  string                 `json:"category_name"`
	CategoryIcon  string                 `json:"category_icon"`
	CategoryColor string                 `json:"category_color"`
	AccountName   pgtype.Text            `json:"account_name"`
}

func (q *Queries) ListTransactionsWithDateRange(ctx context.Context, arg ListTransactionsWithDateRangeParams) ([]ListTransactionsWithDateRangeRow, error) {
	rows, err := q.db.Query(ctx, listTransactionsWithDateRange,
		arg.UserID,
		arg.Limit,
		arg.Offset,
		arg.Column4,
		arg.Column5,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsWithDateRangeRow{}
	for rows.Next() {
		var i ListTransactionsWithDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.AmountCents,
			&i.CategoryID,
			&i.Note,
			&i.CreatedAt,
			&i.CurrencyCode,
			&i.AccountID,
			&i.CategoryName,
			&i.CategoryIcon,
			&i.CategoryColor,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET amount_cents = $3,
    category_id  = $4,
    note         = $5,
    created_at   = $6
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, type, amount_cents, category_id, note, created_at, currency_code, account_id, is_adjustment, snapshot_date
`

type UpdateTransactionParams struct {
	ID          int64              `json:"id"`
	UserID      int64              `json:"user_id"`
	AmountCents int64              `json:"amount_cents"`
	CategoryID  int64              `json:"category_id"`
	Note        string             `json:"note"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.ID,
		arg.UserID,
		arg.AmountCents,
		arg.CategoryID,
		arg.Note,
		arg.CreatedAt,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.AmountCents,
		&i.CategoryID,
		&i.Note,
		&i.CreatedAt,
		&i.CurrencyCode,
		&i.AccountID,
		&i.IsAdjustment,
		&i.SnapshotDate,
	)
	return i, err
}
