// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package sqlcgen

import (
	"context"

	"github.com/horexdev/money-tracker/internal/domain"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUserTransactions = `-- name: CountUserTransactions :one
SELECT count(*)::BIGINT FROM transactions WHERE user_id = $1
`

func (q *Queries) CountUserTransactions(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countUserTransactions, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (user_id, type, amount_cents, category_id, note, currency_code, exchange_rate_snapshot, base_currency_at_creation)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, type, amount_cents, category_id, note, created_at, currency_code, exchange_rate_snapshot, base_currency_at_creation
`

type CreateTransactionParams struct {
	UserID                 int64                  `json:"user_id"`
	Type                   domain.TransactionType `json:"type"`
	AmountCents            int64                  `json:"amount_cents"`
	CategoryID             int64                  `json:"category_id"`
	Note                   string                 `json:"note"`
	CurrencyCode           string                 `json:"currency_code"`
	ExchangeRateSnapshot   pgtype.Numeric         `json:"exchange_rate_snapshot"`
	BaseCurrencyAtCreation string                 `json:"base_currency_at_creation"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.Type,
		arg.AmountCents,
		arg.CategoryID,
		arg.Note,
		arg.CurrencyCode,
		arg.ExchangeRateSnapshot,
		arg.BaseCurrencyAtCreation,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.AmountCents,
		&i.CategoryID,
		&i.Note,
		&i.CreatedAt,
		&i.CurrencyCode,
		&i.ExchangeRateSnapshot,
		&i.BaseCurrencyAtCreation,
	)
	return i, err
}

const createTransactionWithDate = `-- name: CreateTransactionWithDate :one
INSERT INTO transactions (user_id, type, amount_cents, category_id, note, currency_code, exchange_rate_snapshot, base_currency_at_creation, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, type, amount_cents, category_id, note, created_at, currency_code, exchange_rate_snapshot, base_currency_at_creation
`

type CreateTransactionWithDateParams struct {
	UserID                 int64                  `json:"user_id"`
	Type                   domain.TransactionType `json:"type"`
	AmountCents            int64                  `json:"amount_cents"`
	CategoryID             int64                  `json:"category_id"`
	Note                   string                 `json:"note"`
	CurrencyCode           string                 `json:"currency_code"`
	ExchangeRateSnapshot   pgtype.Numeric         `json:"exchange_rate_snapshot"`
	BaseCurrencyAtCreation string                 `json:"base_currency_at_creation"`
	CreatedAt              pgtype.Timestamptz     `json:"created_at"`
}

func (q *Queries) CreateTransactionWithDate(ctx context.Context, arg CreateTransactionWithDateParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransactionWithDate,
		arg.UserID,
		arg.Type,
		arg.AmountCents,
		arg.CategoryID,
		arg.Note,
		arg.CurrencyCode,
		arg.ExchangeRateSnapshot,
		arg.BaseCurrencyAtCreation,
		arg.CreatedAt,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.AmountCents,
		&i.CategoryID,
		&i.Note,
		&i.CreatedAt,
		&i.CurrencyCode,
		&i.ExchangeRateSnapshot,
		&i.BaseCurrencyAtCreation,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions WHERE id = $1 AND user_id = $2
`

type DeleteTransactionParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) error {
	_, err := q.db.Exec(ctx, deleteTransaction, arg.ID, arg.UserID)
	return err
}

const getBalance = `-- name: GetBalance :one
SELECT
    COALESCE(SUM(CASE WHEN type = 'income'  THEN amount_cents ELSE 0 END), 0)::BIGINT AS total_income,
    COALESCE(SUM(CASE WHEN type = 'expense' THEN amount_cents ELSE 0 END), 0)::BIGINT AS total_expense
FROM transactions
WHERE user_id = $1
`

type GetBalanceRow struct {
	TotalIncome  int64 `json:"total_income"`
	TotalExpense int64 `json:"total_expense"`
}

func (q *Queries) GetBalance(ctx context.Context, userID int64) (GetBalanceRow, error) {
	row := q.db.QueryRow(ctx, getBalance, userID)
	var i GetBalanceRow
	err := row.Scan(&i.TotalIncome, &i.TotalExpense)
	return i, err
}

const getBalanceByCurrency = `-- name: GetBalanceByCurrency :many
SELECT
    currency_code,
    COALESCE(SUM(CASE WHEN type = 'income'  THEN amount_cents ELSE 0 END), 0)::BIGINT AS total_income,
    COALESCE(SUM(CASE WHEN type = 'expense' THEN amount_cents ELSE 0 END), 0)::BIGINT AS total_expense
FROM transactions
WHERE user_id = $1
GROUP BY currency_code
`

type GetBalanceByCurrencyRow struct {
	CurrencyCode string `json:"currency_code"`
	TotalIncome  int64  `json:"total_income"`
	TotalExpense int64  `json:"total_expense"`
}

func (q *Queries) GetBalanceByCurrency(ctx context.Context, userID int64) ([]GetBalanceByCurrencyRow, error) {
	rows, err := q.db.Query(ctx, getBalanceByCurrency, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBalanceByCurrencyRow{}
	for rows.Next() {
		var i GetBalanceByCurrencyRow
		if err := rows.Scan(&i.CurrencyCode, &i.TotalIncome, &i.TotalExpense); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatsByCategory = `-- name: GetStatsByCategory :many
SELECT
    c.name              AS category_name,
    c.emoji             AS category_emoji,
    c.color             AS category_color,
    t.type,
    t.currency_code,
    SUM(t.amount_cents)::BIGINT AS total_cents,
    COUNT(*)::BIGINT    AS tx_count
FROM transactions t
JOIN categories c ON c.id = t.category_id
WHERE t.user_id   = $1
  AND t.created_at >= $2
  AND t.created_at <  $3
GROUP BY c.name, c.emoji, c.color, t.type, t.currency_code
ORDER BY total_cents DESC
`

type GetStatsByCategoryParams struct {
	UserID      int64              `json:"user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

type GetStatsByCategoryRow struct {
	CategoryName  string                 `json:"category_name"`
	CategoryEmoji string                 `json:"category_emoji"`
	CategoryColor string                 `json:"category_color"`
	Type          domain.TransactionType `json:"type"`
	CurrencyCode  string                 `json:"currency_code"`
	TotalCents    int64                  `json:"total_cents"`
	TxCount       int64                  `json:"tx_count"`
}

func (q *Queries) GetStatsByCategory(ctx context.Context, arg GetStatsByCategoryParams) ([]GetStatsByCategoryRow, error) {
	rows, err := q.db.Query(ctx, getStatsByCategory, arg.UserID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStatsByCategoryRow{}
	for rows.Next() {
		var i GetStatsByCategoryRow
		if err := rows.Scan(
			&i.CategoryName,
			&i.CategoryEmoji,
			&i.CategoryColor,
			&i.Type,
			&i.CurrencyCode,
			&i.TotalCents,
			&i.TxCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalInBaseCurrency = `-- name: GetTotalInBaseCurrency :one
SELECT COALESCE(
    SUM(
        CASE WHEN type = 'income' THEN amount_cents ELSE -amount_cents END
        * exchange_rate_snapshot
    ), 0
)::BIGINT AS total_net_base_cents
FROM transactions
WHERE user_id = $1
`

// Returns net balance (income - expense) summed across all transactions converted to the user's
// base currency using the exchange_rate_snapshot stored at the time each transaction was created.
func (q *Queries) GetTotalInBaseCurrency(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalInBaseCurrency, userID)
	var total_net_base_cents int64
	err := row.Scan(&total_net_base_cents)
	return total_net_base_cents, err
}

const listTransactions = `-- name: ListTransactions :many
SELECT
    t.id,
    t.user_id,
    t.type,
    t.amount_cents,
    t.category_id,
    t.note,
    t.created_at,
    t.currency_code,
    t.exchange_rate_snapshot,
    t.base_currency_at_creation,
    c.name  AS category_name,
    c.emoji AS category_emoji,
    c.color AS category_color
FROM transactions t
JOIN categories c ON c.id = t.category_id
WHERE t.user_id = $1
ORDER BY t.created_at DESC
LIMIT $2 OFFSET $3
`

type ListTransactionsParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListTransactionsRow struct {
	ID                     int64                  `json:"id"`
	UserID                 int64                  `json:"user_id"`
	Type                   domain.TransactionType `json:"type"`
	AmountCents            int64                  `json:"amount_cents"`
	CategoryID             int64                  `json:"category_id"`
	Note                   string                 `json:"note"`
	CreatedAt              pgtype.Timestamptz     `json:"created_at"`
	CurrencyCode           string                 `json:"currency_code"`
	ExchangeRateSnapshot   pgtype.Numeric         `json:"exchange_rate_snapshot"`
	BaseCurrencyAtCreation string                 `json:"base_currency_at_creation"`
	CategoryName           string                 `json:"category_name"`
	CategoryEmoji          string                 `json:"category_emoji"`
	CategoryColor          string                 `json:"category_color"`
}

func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]ListTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listTransactions, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsRow{}
	for rows.Next() {
		var i ListTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.AmountCents,
			&i.CategoryID,
			&i.Note,
			&i.CreatedAt,
			&i.CurrencyCode,
			&i.ExchangeRateSnapshot,
			&i.BaseCurrencyAtCreation,
			&i.CategoryName,
			&i.CategoryEmoji,
			&i.CategoryColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByCategoryPeriod = `-- name: ListTransactionsByCategoryPeriod :many
SELECT
    t.id,
    t.user_id,
    t.type,
    t.amount_cents,
    t.category_id,
    t.note,
    t.created_at,
    t.currency_code,
    t.exchange_rate_snapshot,
    t.base_currency_at_creation,
    c.name  AS category_name,
    c.emoji AS category_emoji,
    c.color AS category_color
FROM transactions t
JOIN categories c ON c.id = t.category_id
WHERE t.user_id      = $1
  AND t.category_id  = $2
  AND t.type         = 'expense'
  AND t.created_at  >= $3
  AND t.created_at  <  $4
ORDER BY t.created_at DESC
`

type ListTransactionsByCategoryPeriodParams struct {
	UserID      int64              `json:"user_id"`
	CategoryID  int64              `json:"category_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

type ListTransactionsByCategoryPeriodRow struct {
	ID                     int64                  `json:"id"`
	UserID                 int64                  `json:"user_id"`
	Type                   domain.TransactionType `json:"type"`
	AmountCents            int64                  `json:"amount_cents"`
	CategoryID             int64                  `json:"category_id"`
	Note                   string                 `json:"note"`
	CreatedAt              pgtype.Timestamptz     `json:"created_at"`
	CurrencyCode           string                 `json:"currency_code"`
	ExchangeRateSnapshot   pgtype.Numeric         `json:"exchange_rate_snapshot"`
	BaseCurrencyAtCreation string                 `json:"base_currency_at_creation"`
	CategoryName           string                 `json:"category_name"`
	CategoryEmoji          string                 `json:"category_emoji"`
	CategoryColor          string                 `json:"category_color"`
}

func (q *Queries) ListTransactionsByCategoryPeriod(ctx context.Context, arg ListTransactionsByCategoryPeriodParams) ([]ListTransactionsByCategoryPeriodRow, error) {
	rows, err := q.db.Query(ctx, listTransactionsByCategoryPeriod,
		arg.UserID,
		arg.CategoryID,
		arg.CreatedAt,
		arg.CreatedAt_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsByCategoryPeriodRow{}
	for rows.Next() {
		var i ListTransactionsByCategoryPeriodRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.AmountCents,
			&i.CategoryID,
			&i.Note,
			&i.CreatedAt,
			&i.CurrencyCode,
			&i.ExchangeRateSnapshot,
			&i.BaseCurrencyAtCreation,
			&i.CategoryName,
			&i.CategoryEmoji,
			&i.CategoryColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET amount_cents = $3,
    category_id  = $4,
    note         = $5,
    created_at   = $6
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, type, amount_cents, category_id, note, created_at, currency_code, exchange_rate_snapshot, base_currency_at_creation
`

type UpdateTransactionParams struct {
	ID          int64              `json:"id"`
	UserID      int64              `json:"user_id"`
	AmountCents int64              `json:"amount_cents"`
	CategoryID  int64              `json:"category_id"`
	Note        string             `json:"note"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.ID,
		arg.UserID,
		arg.AmountCents,
		arg.CategoryID,
		arg.Note,
		arg.CreatedAt,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.AmountCents,
		&i.CategoryID,
		&i.Note,
		&i.CreatedAt,
		&i.CurrencyCode,
		&i.ExchangeRateSnapshot,
		&i.BaseCurrencyAtCreation,
	)
	return i, err
}
