// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transfers.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTransfersByUser = `-- name: CountTransfersByUser :one
SELECT COUNT(*)::BIGINT FROM transfers WHERE user_id = $1
`

func (q *Queries) CountTransfersByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countTransfersByUser, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createTransfer = `-- name: CreateTransfer :one
INSERT INTO transfers (user_id, from_account_id, to_account_id, amount_cents, from_currency_code, to_currency_code, exchange_rate, note, created_at, from_tx_id, to_tx_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, user_id, from_account_id, to_account_id, amount_cents, from_currency_code, to_currency_code, exchange_rate, note, created_at, from_tx_id, to_tx_id
`

type CreateTransferParams struct {
	UserID           int64              `json:"user_id"`
	FromAccountID    int64              `json:"from_account_id"`
	ToAccountID      int64              `json:"to_account_id"`
	AmountCents      int64              `json:"amount_cents"`
	FromCurrencyCode string             `json:"from_currency_code"`
	ToCurrencyCode   string             `json:"to_currency_code"`
	ExchangeRate     pgtype.Numeric     `json:"exchange_rate"`
	Note             string             `json:"note"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	FromTxID         pgtype.Int8        `json:"from_tx_id"`
	ToTxID           pgtype.Int8        `json:"to_tx_id"`
}

func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error) {
	row := q.db.QueryRow(ctx, createTransfer,
		arg.UserID,
		arg.FromAccountID,
		arg.ToAccountID,
		arg.AmountCents,
		arg.FromCurrencyCode,
		arg.ToCurrencyCode,
		arg.ExchangeRate,
		arg.Note,
		arg.CreatedAt,
		arg.FromTxID,
		arg.ToTxID,
	)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.AmountCents,
		&i.FromCurrencyCode,
		&i.ToCurrencyCode,
		&i.ExchangeRate,
		&i.Note,
		&i.CreatedAt,
		&i.FromTxID,
		&i.ToTxID,
	)
	return i, err
}

const deleteTransfer = `-- name: DeleteTransfer :exec
DELETE FROM transfers WHERE id = $1 AND user_id = $2
`

type DeleteTransferParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteTransfer(ctx context.Context, arg DeleteTransferParams) error {
	_, err := q.db.Exec(ctx, deleteTransfer, arg.ID, arg.UserID)
	return err
}

const getTransferByID = `-- name: GetTransferByID :one
SELECT
    t.id, t.user_id, t.from_account_id, t.to_account_id, t.amount_cents, t.from_currency_code, t.to_currency_code, t.exchange_rate, t.note, t.created_at, t.from_tx_id, t.to_tx_id,
    fa.name AS from_account_name,
    ta.name AS to_account_name
FROM transfers t
JOIN accounts fa ON fa.id = t.from_account_id
JOIN accounts ta ON ta.id = t.to_account_id
WHERE t.id = $1 AND t.user_id = $2
`

type GetTransferByIDParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

type GetTransferByIDRow struct {
	ID               int64              `json:"id"`
	UserID           int64              `json:"user_id"`
	FromAccountID    int64              `json:"from_account_id"`
	ToAccountID      int64              `json:"to_account_id"`
	AmountCents      int64              `json:"amount_cents"`
	FromCurrencyCode string             `json:"from_currency_code"`
	ToCurrencyCode   string             `json:"to_currency_code"`
	ExchangeRate     pgtype.Numeric     `json:"exchange_rate"`
	Note             string             `json:"note"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	FromTxID         pgtype.Int8        `json:"from_tx_id"`
	ToTxID           pgtype.Int8        `json:"to_tx_id"`
	FromAccountName  string             `json:"from_account_name"`
	ToAccountName    string             `json:"to_account_name"`
}

func (q *Queries) GetTransferByID(ctx context.Context, arg GetTransferByIDParams) (GetTransferByIDRow, error) {
	row := q.db.QueryRow(ctx, getTransferByID, arg.ID, arg.UserID)
	var i GetTransferByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.AmountCents,
		&i.FromCurrencyCode,
		&i.ToCurrencyCode,
		&i.ExchangeRate,
		&i.Note,
		&i.CreatedAt,
		&i.FromTxID,
		&i.ToTxID,
		&i.FromAccountName,
		&i.ToAccountName,
	)
	return i, err
}

const getTransferTxIDs = `-- name: GetTransferTxIDs :one
SELECT from_tx_id, to_tx_id FROM transfers WHERE id = $1 AND user_id = $2
`

type GetTransferTxIDsParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

type GetTransferTxIDsRow struct {
	FromTxID pgtype.Int8 `json:"from_tx_id"`
	ToTxID   pgtype.Int8 `json:"to_tx_id"`
}

func (q *Queries) GetTransferTxIDs(ctx context.Context, arg GetTransferTxIDsParams) (GetTransferTxIDsRow, error) {
	row := q.db.QueryRow(ctx, getTransferTxIDs, arg.ID, arg.UserID)
	var i GetTransferTxIDsRow
	err := row.Scan(&i.FromTxID, &i.ToTxID)
	return i, err
}

const listTransfersByAccount = `-- name: ListTransfersByAccount :many
SELECT
    t.id, t.user_id, t.from_account_id, t.to_account_id, t.amount_cents, t.from_currency_code, t.to_currency_code, t.exchange_rate, t.note, t.created_at, t.from_tx_id, t.to_tx_id,
    fa.name AS from_account_name,
    ta.name AS to_account_name
FROM transfers t
JOIN accounts fa ON fa.id = t.from_account_id
JOIN accounts ta ON ta.id = t.to_account_id
WHERE t.user_id = $1
  AND (t.from_account_id = $2 OR t.to_account_id = $2)
ORDER BY t.created_at DESC
`

type ListTransfersByAccountParams struct {
	UserID        int64 `json:"user_id"`
	FromAccountID int64 `json:"from_account_id"`
}

type ListTransfersByAccountRow struct {
	ID               int64              `json:"id"`
	UserID           int64              `json:"user_id"`
	FromAccountID    int64              `json:"from_account_id"`
	ToAccountID      int64              `json:"to_account_id"`
	AmountCents      int64              `json:"amount_cents"`
	FromCurrencyCode string             `json:"from_currency_code"`
	ToCurrencyCode   string             `json:"to_currency_code"`
	ExchangeRate     pgtype.Numeric     `json:"exchange_rate"`
	Note             string             `json:"note"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	FromTxID         pgtype.Int8        `json:"from_tx_id"`
	ToTxID           pgtype.Int8        `json:"to_tx_id"`
	FromAccountName  string             `json:"from_account_name"`
	ToAccountName    string             `json:"to_account_name"`
}

func (q *Queries) ListTransfersByAccount(ctx context.Context, arg ListTransfersByAccountParams) ([]ListTransfersByAccountRow, error) {
	rows, err := q.db.Query(ctx, listTransfersByAccount, arg.UserID, arg.FromAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransfersByAccountRow{}
	for rows.Next() {
		var i ListTransfersByAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FromAccountID,
			&i.ToAccountID,
			&i.AmountCents,
			&i.FromCurrencyCode,
			&i.ToCurrencyCode,
			&i.ExchangeRate,
			&i.Note,
			&i.CreatedAt,
			&i.FromTxID,
			&i.ToTxID,
			&i.FromAccountName,
			&i.ToAccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransfersByUser = `-- name: ListTransfersByUser :many
SELECT
    t.id, t.user_id, t.from_account_id, t.to_account_id, t.amount_cents, t.from_currency_code, t.to_currency_code, t.exchange_rate, t.note, t.created_at, t.from_tx_id, t.to_tx_id,
    fa.name AS from_account_name,
    ta.name AS to_account_name
FROM transfers t
JOIN accounts fa ON fa.id = t.from_account_id
JOIN accounts ta ON ta.id = t.to_account_id
WHERE t.user_id = $1
ORDER BY t.created_at DESC
LIMIT $2 OFFSET $3
`

type ListTransfersByUserParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListTransfersByUserRow struct {
	ID               int64              `json:"id"`
	UserID           int64              `json:"user_id"`
	FromAccountID    int64              `json:"from_account_id"`
	ToAccountID      int64              `json:"to_account_id"`
	AmountCents      int64              `json:"amount_cents"`
	FromCurrencyCode string             `json:"from_currency_code"`
	ToCurrencyCode   string             `json:"to_currency_code"`
	ExchangeRate     pgtype.Numeric     `json:"exchange_rate"`
	Note             string             `json:"note"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	FromTxID         pgtype.Int8        `json:"from_tx_id"`
	ToTxID           pgtype.Int8        `json:"to_tx_id"`
	FromAccountName  string             `json:"from_account_name"`
	ToAccountName    string             `json:"to_account_name"`
}

func (q *Queries) ListTransfersByUser(ctx context.Context, arg ListTransfersByUserParams) ([]ListTransfersByUserRow, error) {
	rows, err := q.db.Query(ctx, listTransfersByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransfersByUserRow{}
	for rows.Next() {
		var i ListTransfersByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FromAccountID,
			&i.ToAccountID,
			&i.AmountCents,
			&i.FromCurrencyCode,
			&i.ToCurrencyCode,
			&i.ExchangeRate,
			&i.Note,
			&i.CreatedAt,
			&i.FromTxID,
			&i.ToTxID,
			&i.FromAccountName,
			&i.ToAccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
