// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: transactions.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/horexdev/money-tracker/internal/domain"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (user_id, type, amount_cents, category_id, note)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, type, amount_cents, category_id, note, created_at
`

type CreateTransactionParams struct {
	UserID      int64                  `json:"user_id"`
	Type        domain.TransactionType `json:"type"`
	AmountCents int64                  `json:"amount_cents"`
	CategoryID  int64                  `json:"category_id"`
	Note        string                 `json:"note"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID, arg.Type, arg.AmountCents, arg.CategoryID, arg.Note,
	)
	var t Transaction
	err := row.Scan(&t.ID, &t.UserID, &t.Type, &t.AmountCents, &t.CategoryID, &t.Note, &t.CreatedAt)
	return t, err
}

const getBalance = `-- name: GetBalance :one
SELECT
    COALESCE(SUM(CASE WHEN type = 'income'  THEN amount_cents ELSE 0 END), 0)::BIGINT AS total_income,
    COALESCE(SUM(CASE WHEN type = 'expense' THEN amount_cents ELSE 0 END), 0)::BIGINT AS total_expense
FROM transactions
WHERE user_id = $1
`

type GetBalanceRow struct {
	TotalIncome  int64 `json:"total_income"`
	TotalExpense int64 `json:"total_expense"`
}

func (q *Queries) GetBalance(ctx context.Context, userID int64) (GetBalanceRow, error) {
	row := q.db.QueryRow(ctx, getBalance, userID)
	var r GetBalanceRow
	err := row.Scan(&r.TotalIncome, &r.TotalExpense)
	return r, err
}

const listTransactions = `-- name: ListTransactions :many
SELECT
    t.id, t.user_id, t.type, t.amount_cents, t.category_id, t.note, t.created_at,
    c.name AS category_name, c.emoji AS category_emoji
FROM transactions t
JOIN categories c ON c.id = t.category_id
WHERE t.user_id = $1
ORDER BY t.created_at DESC
LIMIT $2 OFFSET $3
`

type ListTransactionsRow struct {
	ID            int64                  `json:"id"`
	UserID        int64                  `json:"user_id"`
	Type          domain.TransactionType `json:"type"`
	AmountCents   int64                  `json:"amount_cents"`
	CategoryID    int64                  `json:"category_id"`
	Note          string                 `json:"note"`
	CreatedAt     time.Time              `json:"created_at"`
	CategoryName  string                 `json:"category_name"`
	CategoryEmoji string                 `json:"category_emoji"`
}

type ListTransactionsParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]ListTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listTransactions, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []ListTransactionsRow
	for rows.Next() {
		var r ListTransactionsRow
		if err := rows.Scan(
			&r.ID, &r.UserID, &r.Type, &r.AmountCents,
			&r.CategoryID, &r.Note, &r.CreatedAt,
			&r.CategoryName, &r.CategoryEmoji,
		); err != nil {
			return nil, err
		}
		items = append(items, r)
	}
	return items, rows.Err()
}

const getStatsByCategory = `-- name: GetStatsByCategory :many
SELECT
    c.name              AS category_name,
    c.emoji             AS category_emoji,
    t.type,
    SUM(t.amount_cents)::BIGINT AS total_cents,
    COUNT(*)::BIGINT    AS tx_count
FROM transactions t
JOIN categories c ON c.id = t.category_id
WHERE t.user_id   = $1
  AND t.created_at >= $2
  AND t.created_at <  $3
GROUP BY c.name, c.emoji, t.type
ORDER BY total_cents DESC
`

type GetStatsByCategoryRow struct {
	CategoryName  string                 `json:"category_name"`
	CategoryEmoji string                 `json:"category_emoji"`
	Type          domain.TransactionType `json:"type"`
	TotalCents    int64                  `json:"total_cents"`
	TxCount       int64                  `json:"tx_count"`
}

type GetStatsByCategoryParams struct {
	UserID    int64     `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	EndAt     time.Time `json:"end_at"`
}

func (q *Queries) GetStatsByCategory(ctx context.Context, arg GetStatsByCategoryParams) ([]GetStatsByCategoryRow, error) {
	rows, err := q.db.Query(ctx, getStatsByCategory, arg.UserID, arg.CreatedAt, arg.EndAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []GetStatsByCategoryRow
	for rows.Next() {
		var r GetStatsByCategoryRow
		if err := rows.Scan(
			&r.CategoryName, &r.CategoryEmoji, &r.Type, &r.TotalCents, &r.TxCount,
		); err != nil {
			return nil, err
		}
		items = append(items, r)
	}
	return items, rows.Err()
}
