// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transaction_templates.sql

package sqlcgen

import (
	"context"

	"github.com/horexdev/money-tracker/internal/domain"
	"github.com/jackc/pgx/v5/pgtype"
)

const countTransactionTemplatesByAccount = `-- name: CountTransactionTemplatesByAccount :one
SELECT COUNT(*) FROM transaction_templates WHERE account_id = $1
`

func (q *Queries) CountTransactionTemplatesByAccount(ctx context.Context, accountID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactionTemplatesByAccount, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTransactionTemplatesByCategory = `-- name: CountTransactionTemplatesByCategory :one
SELECT COUNT(*) FROM transaction_templates WHERE category_id = $1
`

func (q *Queries) CountTransactionTemplatesByCategory(ctx context.Context, categoryID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactionTemplatesByCategory, categoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTransactionTemplate = `-- name: CreateTransactionTemplate :one
INSERT INTO transaction_templates (
    user_id, name, type, amount_cents, amount_fixed,
    category_id, account_id, currency_code, note, sort_order
)
VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    COALESCE(
        (SELECT MAX(sort_order) + 1 FROM transaction_templates WHERE user_id = $1),
        0
    )
)
RETURNING id, user_id, name, type, amount_cents, amount_fixed, category_id, account_id, currency_code, note, sort_order, created_at, updated_at
`

type CreateTransactionTemplateParams struct {
	UserID       int64                  `json:"user_id"`
	Name         string                 `json:"name"`
	Type         domain.TransactionType `json:"type"`
	AmountCents  int64                  `json:"amount_cents"`
	AmountFixed  bool                   `json:"amount_fixed"`
	CategoryID   int64                  `json:"category_id"`
	AccountID    int64                  `json:"account_id"`
	CurrencyCode string                 `json:"currency_code"`
	Note         string                 `json:"note"`
}

func (q *Queries) CreateTransactionTemplate(ctx context.Context, arg CreateTransactionTemplateParams) (TransactionTemplate, error) {
	row := q.db.QueryRow(ctx, createTransactionTemplate,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.AmountCents,
		arg.AmountFixed,
		arg.CategoryID,
		arg.AccountID,
		arg.CurrencyCode,
		arg.Note,
	)
	var i TransactionTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.AmountCents,
		&i.AmountFixed,
		&i.CategoryID,
		&i.AccountID,
		&i.CurrencyCode,
		&i.Note,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTransactionTemplate = `-- name: DeleteTransactionTemplate :execrows
DELETE FROM transaction_templates WHERE id = $1 AND user_id = $2
`

type DeleteTransactionTemplateParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteTransactionTemplate(ctx context.Context, arg DeleteTransactionTemplateParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTransactionTemplate, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTransactionTemplateByID = `-- name: GetTransactionTemplateByID :one
SELECT
    t.id, t.user_id, t.name, t.type, t.amount_cents, t.amount_fixed, t.category_id, t.account_id, t.currency_code, t.note, t.sort_order, t.created_at, t.updated_at,
    c.name  AS category_name,
    c.icon  AS category_icon,
    c.color AS category_color
FROM transaction_templates t
JOIN categories c ON c.id = t.category_id
WHERE t.id = $1 AND t.user_id = $2
`

type GetTransactionTemplateByIDParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

type GetTransactionTemplateByIDRow struct {
	ID            int64                  `json:"id"`
	UserID        int64                  `json:"user_id"`
	Name          string                 `json:"name"`
	Type          domain.TransactionType `json:"type"`
	AmountCents   int64                  `json:"amount_cents"`
	AmountFixed   bool                   `json:"amount_fixed"`
	CategoryID    int64                  `json:"category_id"`
	AccountID     int64                  `json:"account_id"`
	CurrencyCode  string                 `json:"currency_code"`
	Note          string                 `json:"note"`
	SortOrder     int32                  `json:"sort_order"`
	CreatedAt     pgtype.Timestamptz     `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz     `json:"updated_at"`
	CategoryName  string                 `json:"category_name"`
	CategoryIcon  string                 `json:"category_icon"`
	CategoryColor string                 `json:"category_color"`
}

func (q *Queries) GetTransactionTemplateByID(ctx context.Context, arg GetTransactionTemplateByIDParams) (GetTransactionTemplateByIDRow, error) {
	row := q.db.QueryRow(ctx, getTransactionTemplateByID, arg.ID, arg.UserID)
	var i GetTransactionTemplateByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.AmountCents,
		&i.AmountFixed,
		&i.CategoryID,
		&i.AccountID,
		&i.CurrencyCode,
		&i.Note,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryName,
		&i.CategoryIcon,
		&i.CategoryColor,
	)
	return i, err
}

const listTransactionTemplatesByUser = `-- name: ListTransactionTemplatesByUser :many
SELECT
    t.id, t.user_id, t.name, t.type, t.amount_cents, t.amount_fixed, t.category_id, t.account_id, t.currency_code, t.note, t.sort_order, t.created_at, t.updated_at,
    c.name  AS category_name,
    c.icon  AS category_icon,
    c.color AS category_color
FROM transaction_templates t
JOIN categories c ON c.id = t.category_id
WHERE t.user_id = $1
ORDER BY t.sort_order ASC, t.created_at ASC
`

type ListTransactionTemplatesByUserRow struct {
	ID            int64                  `json:"id"`
	UserID        int64                  `json:"user_id"`
	Name          string                 `json:"name"`
	Type          domain.TransactionType `json:"type"`
	AmountCents   int64                  `json:"amount_cents"`
	AmountFixed   bool                   `json:"amount_fixed"`
	CategoryID    int64                  `json:"category_id"`
	AccountID     int64                  `json:"account_id"`
	CurrencyCode  string                 `json:"currency_code"`
	Note          string                 `json:"note"`
	SortOrder     int32                  `json:"sort_order"`
	CreatedAt     pgtype.Timestamptz     `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz     `json:"updated_at"`
	CategoryName  string                 `json:"category_name"`
	CategoryIcon  string                 `json:"category_icon"`
	CategoryColor string                 `json:"category_color"`
}

func (q *Queries) ListTransactionTemplatesByUser(ctx context.Context, userID int64) ([]ListTransactionTemplatesByUserRow, error) {
	rows, err := q.db.Query(ctx, listTransactionTemplatesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionTemplatesByUserRow{}
	for rows.Next() {
		var i ListTransactionTemplatesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.AmountCents,
			&i.AmountFixed,
			&i.CategoryID,
			&i.AccountID,
			&i.CurrencyCode,
			&i.Note,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.CategoryIcon,
			&i.CategoryColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransactionTemplate = `-- name: UpdateTransactionTemplate :one
UPDATE transaction_templates
SET name          = $3,
    type          = $4,
    amount_cents  = $5,
    amount_fixed  = $6,
    category_id   = $7,
    account_id    = $8,
    currency_code = $9,
    note          = $10,
    updated_at    = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, type, amount_cents, amount_fixed, category_id, account_id, currency_code, note, sort_order, created_at, updated_at
`

type UpdateTransactionTemplateParams struct {
	ID           int64                  `json:"id"`
	UserID       int64                  `json:"user_id"`
	Name         string                 `json:"name"`
	Type         domain.TransactionType `json:"type"`
	AmountCents  int64                  `json:"amount_cents"`
	AmountFixed  bool                   `json:"amount_fixed"`
	CategoryID   int64                  `json:"category_id"`
	AccountID    int64                  `json:"account_id"`
	CurrencyCode string                 `json:"currency_code"`
	Note         string                 `json:"note"`
}

func (q *Queries) UpdateTransactionTemplate(ctx context.Context, arg UpdateTransactionTemplateParams) (TransactionTemplate, error) {
	row := q.db.QueryRow(ctx, updateTransactionTemplate,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.AmountCents,
		arg.AmountFixed,
		arg.CategoryID,
		arg.AccountID,
		arg.CurrencyCode,
		arg.Note,
	)
	var i TransactionTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.AmountCents,
		&i.AmountFixed,
		&i.CategoryID,
		&i.AccountID,
		&i.CurrencyCode,
		&i.Note,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTransactionTemplateSortOrder = `-- name: UpdateTransactionTemplateSortOrder :execrows
UPDATE transaction_templates
SET sort_order = $3,
    updated_at = now()
WHERE id = $1 AND user_id = $2
`

type UpdateTransactionTemplateSortOrderParams struct {
	ID        int64 `json:"id"`
	UserID    int64 `json:"user_id"`
	SortOrder int32 `json:"sort_order"`
}

func (q *Queries) UpdateTransactionTemplateSortOrder(ctx context.Context, arg UpdateTransactionTemplateSortOrderParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTransactionTemplateSortOrder, arg.ID, arg.UserID, arg.SortOrder)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
