// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlcgen

import (
	"context"
)

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, first_name, last_name, currency_code, created_at, updated_at, display_currencies, language FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.CurrencyCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayCurrencies,
		&i.Language,
	)
	return i, err
}

const updateDisplayCurrencies = `-- name: UpdateDisplayCurrencies :one
UPDATE users
SET display_currencies = $2,
    updated_at         = NOW()
WHERE id = $1
RETURNING id, username, first_name, last_name, currency_code, created_at, updated_at, display_currencies, language
`

type UpdateDisplayCurrenciesParams struct {
	ID                int64  `json:"id"`
	DisplayCurrencies string `json:"display_currencies"`
}

func (q *Queries) UpdateDisplayCurrencies(ctx context.Context, arg UpdateDisplayCurrenciesParams) (User, error) {
	row := q.db.QueryRow(ctx, updateDisplayCurrencies, arg.ID, arg.DisplayCurrencies)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.CurrencyCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayCurrencies,
		&i.Language,
	)
	return i, err
}

const updateUserCurrency = `-- name: UpdateUserCurrency :one
UPDATE users
SET currency_code = $2,
    updated_at    = NOW()
WHERE id = $1
RETURNING id, username, first_name, last_name, currency_code, created_at, updated_at, display_currencies, language
`

type UpdateUserCurrencyParams struct {
	ID           int64  `json:"id"`
	CurrencyCode string `json:"currency_code"`
}

func (q *Queries) UpdateUserCurrency(ctx context.Context, arg UpdateUserCurrencyParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserCurrency, arg.ID, arg.CurrencyCode)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.CurrencyCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayCurrencies,
		&i.Language,
	)
	return i, err
}

const updateUserLanguage = `-- name: UpdateUserLanguage :one
UPDATE users
SET language   = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, username, first_name, last_name, currency_code, created_at, updated_at, display_currencies, language
`

type UpdateUserLanguageParams struct {
	ID       int64  `json:"id"`
	Language string `json:"language"`
}

func (q *Queries) UpdateUserLanguage(ctx context.Context, arg UpdateUserLanguageParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserLanguage, arg.ID, arg.Language)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.CurrencyCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayCurrencies,
		&i.Language,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (id, username, first_name, last_name, currency_code)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE
    SET username   = EXCLUDED.username,
        first_name = EXCLUDED.first_name,
        last_name  = EXCLUDED.last_name,
        updated_at = NOW()
RETURNING id, username, first_name, last_name, currency_code, created_at, updated_at, display_currencies, language
`

type UpsertUserParams struct {
	ID           int64  `json:"id"`
	Username     string `json:"username"`
	FirstName    string `json:"first_name"`
	LastName     string `json:"last_name"`
	CurrencyCode string `json:"currency_code"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.ID,
		arg.Username,
		arg.FirstName,
		arg.LastName,
		arg.CurrencyCode,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.CurrencyCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayCurrencies,
		&i.Language,
	)
	return i, err
}
