// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAllUserAccounts = `-- name: DeleteAllUserAccounts :exec
DELETE FROM accounts WHERE user_id = $1
`

func (q *Queries) DeleteAllUserAccounts(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteAllUserAccounts, userID)
	return err
}

const deleteAllUserBudgets = `-- name: DeleteAllUserBudgets :exec
DELETE FROM budgets WHERE user_id = $1
`

func (q *Queries) DeleteAllUserBudgets(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteAllUserBudgets, userID)
	return err
}

const deleteAllUserCategories = `-- name: DeleteAllUserCategories :exec
DELETE FROM categories WHERE user_id = $1
`

func (q *Queries) DeleteAllUserCategories(ctx context.Context, userID pgtype.Int8) error {
	_, err := q.db.Exec(ctx, deleteAllUserCategories, userID)
	return err
}

const deleteAllUserGoals = `-- name: DeleteAllUserGoals :exec
DELETE FROM savings_goals WHERE user_id = $1
`

func (q *Queries) DeleteAllUserGoals(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteAllUserGoals, userID)
	return err
}

const deleteAllUserRecurring = `-- name: DeleteAllUserRecurring :exec
DELETE FROM recurring_transactions WHERE user_id = $1
`

func (q *Queries) DeleteAllUserRecurring(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteAllUserRecurring, userID)
	return err
}

const deleteAllUserTransactions = `-- name: DeleteAllUserTransactions :exec
DELETE FROM transactions WHERE user_id = $1
`

func (q *Queries) DeleteAllUserTransactions(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteAllUserTransactions, userID)
	return err
}

const deleteAllUserTransfers = `-- name: DeleteAllUserTransfers :exec
DELETE FROM transfers WHERE user_id = $1
`

func (q *Queries) DeleteAllUserTransfers(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteAllUserTransfers, userID)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, first_name, last_name, created_at, updated_at, display_currencies, language, notify_budget_alerts, notify_recurring_reminders, notify_weekly_summary, notify_goal_milestones FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayCurrencies,
		&i.Language,
		&i.NotifyBudgetAlerts,
		&i.NotifyRecurringReminders,
		&i.NotifyWeeklySummary,
		&i.NotifyGoalMilestones,
	)
	return i, err
}

const updateDisplayCurrencies = `-- name: UpdateDisplayCurrencies :one
UPDATE users
SET display_currencies = $2,
    updated_at         = NOW()
WHERE id = $1
RETURNING id, username, first_name, last_name, created_at, updated_at, display_currencies, language, notify_budget_alerts, notify_recurring_reminders, notify_weekly_summary, notify_goal_milestones
`

type UpdateDisplayCurrenciesParams struct {
	ID                int64  `json:"id"`
	DisplayCurrencies string `json:"display_currencies"`
}

func (q *Queries) UpdateDisplayCurrencies(ctx context.Context, arg UpdateDisplayCurrenciesParams) (User, error) {
	row := q.db.QueryRow(ctx, updateDisplayCurrencies, arg.ID, arg.DisplayCurrencies)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayCurrencies,
		&i.Language,
		&i.NotifyBudgetAlerts,
		&i.NotifyRecurringReminders,
		&i.NotifyWeeklySummary,
		&i.NotifyGoalMilestones,
	)
	return i, err
}

const updateNotificationPreferences = `-- name: UpdateNotificationPreferences :one
UPDATE users
SET notify_budget_alerts       = $2,
    notify_recurring_reminders = $3,
    notify_weekly_summary      = $4,
    notify_goal_milestones     = $5,
    updated_at                 = NOW()
WHERE id = $1
RETURNING id, username, first_name, last_name, created_at, updated_at, display_currencies, language, notify_budget_alerts, notify_recurring_reminders, notify_weekly_summary, notify_goal_milestones
`

type UpdateNotificationPreferencesParams struct {
	ID                       int64 `json:"id"`
	NotifyBudgetAlerts       bool  `json:"notify_budget_alerts"`
	NotifyRecurringReminders bool  `json:"notify_recurring_reminders"`
	NotifyWeeklySummary      bool  `json:"notify_weekly_summary"`
	NotifyGoalMilestones     bool  `json:"notify_goal_milestones"`
}

func (q *Queries) UpdateNotificationPreferences(ctx context.Context, arg UpdateNotificationPreferencesParams) (User, error) {
	row := q.db.QueryRow(ctx, updateNotificationPreferences,
		arg.ID,
		arg.NotifyBudgetAlerts,
		arg.NotifyRecurringReminders,
		arg.NotifyWeeklySummary,
		arg.NotifyGoalMilestones,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayCurrencies,
		&i.Language,
		&i.NotifyBudgetAlerts,
		&i.NotifyRecurringReminders,
		&i.NotifyWeeklySummary,
		&i.NotifyGoalMilestones,
	)
	return i, err
}

const updateUserLanguage = `-- name: UpdateUserLanguage :one
UPDATE users
SET language   = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, username, first_name, last_name, created_at, updated_at, display_currencies, language, notify_budget_alerts, notify_recurring_reminders, notify_weekly_summary, notify_goal_milestones
`

type UpdateUserLanguageParams struct {
	ID       int64  `json:"id"`
	Language string `json:"language"`
}

func (q *Queries) UpdateUserLanguage(ctx context.Context, arg UpdateUserLanguageParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserLanguage, arg.ID, arg.Language)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayCurrencies,
		&i.Language,
		&i.NotifyBudgetAlerts,
		&i.NotifyRecurringReminders,
		&i.NotifyWeeklySummary,
		&i.NotifyGoalMilestones,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (id, username, first_name, last_name, language)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE
    SET username      = EXCLUDED.username,
        first_name    = EXCLUDED.first_name,
        last_name     = EXCLUDED.last_name,
        language      = CASE WHEN users.language = '' OR users.language IS NULL THEN EXCLUDED.language ELSE users.language END,
        updated_at    = NOW()
RETURNING id, username, first_name, last_name, created_at, updated_at, display_currencies, language, notify_budget_alerts, notify_recurring_reminders, notify_weekly_summary, notify_goal_milestones
`

type UpsertUserParams struct {
	ID        int64  `json:"id"`
	Username  string `json:"username"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Language  string `json:"language"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.ID,
		arg.Username,
		arg.FirstName,
		arg.LastName,
		arg.Language,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayCurrencies,
		&i.Language,
		&i.NotifyBudgetAlerts,
		&i.NotifyRecurringReminders,
		&i.NotifyWeeklySummary,
		&i.NotifyGoalMilestones,
	)
	return i, err
}
